In [ ]:
from google.colab import files
uploaded = files.upload()

Saving retail_transactions_100k.csv to retail_transactions_100k.csv

In [ ]:
from pyspark.sql import SparkSession
spark = SparkSession.builder \
    .appName("RetailDataAnalysis") \
    .getOrCreate()

In [ ]:
df = spark.read.csv(
    "retail_transactions_100k.csv",
    header=True,
    inferSchema=True
)

In [ ]:
df.show(5)

+--------+----------+-----------+--------------+---------+------+----------+---------------+-----------+--------+----------+------------+--------------+---------+------+
|order_id|order_date|customer_id| customer_name|     city|region|product_id|   product_name|   category|quantity|unit_price|discount_pct|payment_method|   status|rating|
+--------+----------+-----------+--------------+---------+------+----------+---------------+-----------+--------+----------+------------+--------------+---------+------+
| O000001|2026-02-27|     C00205|Customer_00205|     Pune|  West|      P004|27 Inch Monitor|Electronics|       2|  16961.87|           0|           COD|Delivered|  NULL|
| O000002|2026-04-22|     C01906|Customer_01906|  Lucknow| North|      P010|     Web Camera|Accessories|       1|   4241.16|          20|   Net Banking|Delivered|     1|
| O000003|2026-03-23|     C03463|Customer_03463|Ahmedabad|  West|      P005|   Office Chair|  Furniture|       2|   8590.05|          10|           UPI|Delivered|     5|
| O000004|2026-05-16|     C00356|Customer_00356|   Jaipur| North|      P009|    Smart Watch|Electronics|       1|  12908.38|          10|           UPI|Delivered|     3|
| O000005|2026-10-23|     C01576|Customer_01576|Bangalore| South|      P001|     Laptop Pro|Electronics|       2|  67839.91|           0|   Credit Card|Cancelled|  NULL|
+--------+----------+-----------+--------------+---------+------+----------+---------------+-----------+--------+----------+------------+--------------+---------+------+
only showing top 5 rows

In [ ]:
df.printSchema()

root
 |-- order_id: string (nullable = true)
 |-- order_date: date (nullable = true)
 |-- customer_id: string (nullable = true)
 |-- customer_name: string (nullable = true)
 |-- city: string (nullable = true)
 |-- region: string (nullable = true)
 |-- product_id: string (nullable = true)
 |-- product_name: string (nullable = true)
 |-- category: string (nullable = true)
 |-- quantity: integer (nullable = true)
 |-- unit_price: double (nullable = true)
 |-- discount_pct: integer (nullable = true)
 |-- payment_method: string (nullable = true)
 |-- status: string (nullable = true)
 |-- rating: integer (nullable = true)

In [ ]:
print("Total records:", df.count())

Total records: 100000

In [ ]:
# 1. Display the first 20 records
df.show(20)

# 2. Display the schema
df.printSchema()

# 3. Display all column names
print(df.columns)

# 4. Count the total number of records
df.count()

# 5. Display specific columns (order ID, product name, city, quantity, unit price)
df.select("order_id", "product_name", "city", "quantity", "unit_price").show()

# 6. Display only Electronics transactions
df.filter(df.category == "Electronics").show()

# 7. Display transactions from Hyderabad
df.filter(df.city == "Hyderabad").show()

# 8. Display transactions where quantity is greater than 3
df.filter(df.quantity > 3).show()

# 9. Display transactions where unit price is greater than 20,000
df.filter(df.unit_price > 20000).show()

# 10. Display Delivered transactions
df.filter(df.status == "Delivered").show()

+--------+----------+-----------+--------------+---------+------+----------+-------------------+-----------+--------+----------+------------+--------------+----------+------+
|order_id|order_date|customer_id| customer_name|     city|region|product_id|       product_name|   category|quantity|unit_price|discount_pct|payment_method|    status|rating|
+--------+----------+-----------+--------------+---------+------+----------+-------------------+-----------+--------+----------+------------+--------------+----------+------+
| O000001|2026-02-27|     C00205|Customer_00205|     Pune|  West|      P004|    27 Inch Monitor|Electronics|       2|  16961.87|           0|           COD| Delivered|  NULL|
| O000002|2026-04-22|     C01906|Customer_01906|  Lucknow| North|      P010|         Web Camera|Accessories|       1|   4241.16|          20|   Net Banking| Delivered|     1|
| O000003|2026-03-23|     C03463|Customer_03463|Ahmedabad|  West|      P005|       Office Chair|  Furniture|       2|   8590.05|          10|           UPI| Delivered|     5|
| O000004|2026-05-16|     C00356|Customer_00356|   Jaipur| North|      P009|        Smart Watch|Electronics|       1|  12908.38|          10|           UPI| Delivered|     3|
| O000005|2026-10-23|     C01576|Customer_01576|Bangalore| South|      P001|         Laptop Pro|Electronics|       2|  67839.91|           0|   Credit Card| Cancelled|  NULL|
| O000006|2026-08-21|     C02989|Customer_02989|  Chennai| South|      P006|         Study Desk|  Furniture|       3|   13349.3|           5|           UPI|   Shipped|  NULL|
| O000007|2026-05-06|     C01339|Customer_01339|   Jaipur| North|      P007|             Tablet|Electronics|       3|  30193.06|          20|   Credit Card|   Shipped|  NULL|
| O000008|2026-01-29|     C01877|Customer_01877|Hyderabad| South|      P006|         Study Desk|  Furniture|       4|  13479.74|           5|           COD| Cancelled|  NULL|
| O000009|2026-09-13|     C03242|Customer_03242|   Jaipur| North|      P003|Mechanical Keyboard|Accessories|       3|   4240.53|          20|           COD| Delivered|     4|
| O000010|2026-07-05|     C01797|Customer_01797|  Chennai| South|      P009|        Smart Watch|Electronics|       4|  11214.55|           0|           UPI| Delivered|     5|
| O000011|2026-02-02|     C03153|Customer_03153|    Delhi| North|      P010|         Web Camera|Accessories|       4|   4219.56|          20|           UPI|   Shipped|  NULL|
| O000012|2026-10-02|     C02186|Customer_02186|Ahmedabad|  West|      P002|     Wireless Mouse|Accessories|       3|   1484.34|          15|           UPI|  Returned|  NULL|
| O000013|2026-05-15|     C04101|Customer_04101|  Chennai| South|      P009|        Smart Watch|Electronics|       1|   12711.4|           5|           COD|   Shipped|  NULL|
| O000014|2026-03-24|     C04419|Customer_04419|  Lucknow| North|      P001|         Laptop Pro|Electronics|       5|  63171.22|           0|           UPI| Cancelled|  NULL|
| O000015|2026-06-07|     C01962|Customer_01962|Hyderabad| South|      P004|    27 Inch Monitor|Electronics|       5|  19287.21|           0|   Net Banking|Processing|  NULL|
| O000016|2026-09-30|     C01031|Customer_01031|  Chennai| South|      P011|            Printer|Electronics|       4|  17143.93|           0|    Debit Card| Delivered|     5|
| O000017|2026-04-13|     C02554|Customer_02554|    Delhi| North|      P011|            Printer|Electronics|       3|  15841.54|          20|   Net Banking| Delivered|     5|
| O000018|2026-10-11|     C01886|Customer_01886|  Kolkata|  East|      P004|    27 Inch Monitor|Electronics|       1|  16764.46|           0|   Credit Card| Delivered|     5|
| O000019|2026-05-02|     C02282|Customer_02282|   Jaipur| North|      P004|    27 Inch Monitor|Electronics|       5|  16941.06|          15|   Credit Card|Processing|  NULL|
| O000020|2026-04-08|     C00773|Customer_00773|Bangalore| South|      P011|            Printer|Electronics|       4|   15627.0|          10|   Net Banking| Cancelled|  NULL|
+--------+----------+-----------+--------------+---------+------+----------+-------------------+-----------+--------+----------+------------+--------------+----------+------+
only showing top 20 rows
root
 |-- order_id: string (nullable = true)
 |-- order_date: date (nullable = true)
 |-- customer_id: string (nullable = true)
 |-- customer_name: string (nullable = true)
 |-- city: string (nullable = true)
 |-- region: string (nullable = true)
 |-- product_id: string (nullable = true)
 |-- product_name: string (nullable = true)
 |-- category: string (nullable = true)
 |-- quantity: integer (nullable = true)
 |-- unit_price: double (nullable = true)
 |-- discount_pct: integer (nullable = true)
 |-- payment_method: string (nullable = true)
 |-- status: string (nullable = true)
 |-- rating: integer (nullable = true)

['order_id', 'order_date', 'customer_id', 'customer_name', 'city', 'region', 'product_id', 'product_name', 'category', 'quantity', 'unit_price', 'discount_pct', 'payment_method', 'status', 'rating']
+--------+-------------------+---------+--------+----------+
|order_id|       product_name|     city|quantity|unit_price|
+--------+-------------------+---------+--------+----------+
| O000001|    27 Inch Monitor|     Pune|       2|  16961.87|
| O000002|         Web Camera|  Lucknow|       1|   4241.16|
| O000003|       Office Chair|Ahmedabad|       2|   8590.05|
| O000004|        Smart Watch|   Jaipur|       1|  12908.38|
| O000005|         Laptop Pro|Bangalore|       2|  67839.91|
| O000006|         Study Desk|  Chennai|       3|   13349.3|
| O000007|             Tablet|   Jaipur|       3|  30193.06|
| O000008|         Study Desk|Hyderabad|       4|  13479.74|
| O000009|Mechanical Keyboard|   Jaipur|       3|   4240.53|
| O000010|        Smart Watch|  Chennai|       4|  11214.55|
| O000011|         Web Camera|    Delhi|       4|   4219.56|
| O000012|     Wireless Mouse|Ahmedabad|       3|   1484.34|
| O000013|        Smart Watch|  Chennai|       1|   12711.4|
| O000014|         Laptop Pro|  Lucknow|       5|  63171.22|
| O000015|    27 Inch Monitor|Hyderabad|       5|  19287.21|
| O000016|            Printer|  Chennai|       4|  17143.93|
| O000017|            Printer|    Delhi|       3|  15841.54|
| O000018|    27 Inch Monitor|  Kolkata|       1|  16764.46|
| O000019|    27 Inch Monitor|   Jaipur|       5|  16941.06|
| O000020|            Printer|Bangalore|       4|   15627.0|
+--------+-------------------+---------+--------+----------+
only showing top 20 rows
+--------+----------+-----------+--------------+---------+------+----------+---------------+-----------+--------+----------+------------+--------------+----------+------+
|order_id|order_date|customer_id| customer_name|     city|region|product_id|   product_name|   category|quantity|unit_price|discount_pct|payment_method|    status|rating|
+--------+----------+-----------+--------------+---------+------+----------+---------------+-----------+--------+----------+------------+--------------+----------+------+
| O000001|2026-02-27|     C00205|Customer_00205|     Pune|  West|      P004|27 Inch Monitor|Electronics|       2|  16961.87|           0|           COD| Delivered|  NULL|
| O000004|2026-05-16|     C00356|Customer_00356|   Jaipur| North|      P009|    Smart Watch|Electronics|       1|  12908.38|          10|           UPI| Delivered|     3|
| O000005|2026-10-23|     C01576|Customer_01576|Bangalore| South|      P001|     Laptop Pro|Electronics|       2|  67839.91|           0|   Credit Card| Cancelled|  NULL|
| O000007|2026-05-06|     C01339|Customer_01339|   Jaipur| North|      P007|         Tablet|Electronics|       3|  30193.06|          20|   Credit Card|   Shipped|  NULL|
| O000010|2026-07-05|     C01797|Customer_01797|  Chennai| South|      P009|    Smart Watch|Electronics|       4|  11214.55|           0|           UPI| Delivered|     5|
| O000013|2026-05-15|     C04101|Customer_04101|  Chennai| South|      P009|    Smart Watch|Electronics|       1|   12711.4|           5|           COD|   Shipped|  NULL|
| O000014|2026-03-24|     C04419|Customer_04419|  Lucknow| North|      P001|     Laptop Pro|Electronics|       5|  63171.22|           0|           UPI| Cancelled|  NULL|
| O000015|2026-06-07|     C01962|Customer_01962|Hyderabad| South|      P004|27 Inch Monitor|Electronics|       5|  19287.21|           0|   Net Banking|Processing|  NULL|
| O000016|2026-09-30|     C01031|Customer_01031|  Chennai| South|      P011|        Printer|Electronics|       4|  17143.93|           0|    Debit Card| Delivered|     5|
| O000017|2026-04-13|     C02554|Customer_02554|    Delhi| North|      P011|        Printer|Electronics|       3|  15841.54|          20|   Net Banking| Delivered|     5|
| O000018|2026-10-11|     C01886|Customer_01886|  Kolkata|  East|      P004|27 Inch Monitor|Electronics|       1|  16764.46|           0|   Credit Card| Delivered|     5|
| O000019|2026-05-02|     C02282|Customer_02282|   Jaipur| North|      P004|27 Inch Monitor|Electronics|       5|  16941.06|          15|   Credit Card|Processing|  NULL|
| O000020|2026-04-08|     C00773|Customer_00773|Bangalore| South|      P011|        Printer|Electronics|       4|   15627.0|          10|   Net Banking| Cancelled|  NULL|
| O000024|2026-05-27|     C03466|Customer_03466|  Lucknow| North|      P011|        Printer|Electronics|       4|  15116.28|           5|   Credit Card|  Returned|  NULL|
| O000025|2026-10-05|     C00500|Customer_00500|Ahmedabad|  West|      P001|     Laptop Pro|Electronics|       1|  65875.45|          20|           COD| Delivered|     2|
| O000026|2026-02-05|     C04875|Customer_04875|Bangalore| South|      P011|        Printer|Electronics|       2|  15753.67|           5|           COD|   Shipped|  NULL|
| O000027|2026-08-03|     C04782|Customer_04782|  Kolkata|  East|      P009|    Smart Watch|Electronics|       3|  12834.64|           5|    Debit Card| Delivered|     3|
| O000028|2026-08-23|     C02591|Customer_02591|Bangalore| South|      P001|     Laptop Pro|Electronics|       4|  66260.06|           0|           UPI| Delivered|     3|
| O000032|2026-08-05|     C02267|Customer_02267|Hyderabad| South|      P001|     Laptop Pro|Electronics|       3|  67819.64|           5|   Credit Card|Processing|  NULL|
| O000038|2026-05-23|     C02877|Customer_02877|  Lucknow| North|      P007|         Tablet|Electronics|       5|  27243.55|           0|           UPI| Cancelled|  NULL|
+--------+----------+-----------+--------------+---------+------+----------+---------------+-----------+--------+----------+------------+--------------+----------+------+
only showing top 20 rows
+--------+----------+-----------+--------------+---------+------+----------+---------------+-----------+--------+----------+------------+--------------+----------+------+
|order_id|order_date|customer_id| customer_name|     city|region|product_id|   product_name|   category|quantity|unit_price|discount_pct|payment_method|    status|rating|
+--------+----------+-----------+--------------+---------+------+----------+---------------+-----------+--------+----------+------------+--------------+----------+------+
| O000008|2026-01-29|     C01877|Customer_01877|Hyderabad| South|      P006|     Study Desk|  Furniture|       4|  13479.74|           5|           COD| Cancelled|  NULL|
| O000015|2026-06-07|     C01962|Customer_01962|Hyderabad| South|      P004|27 Inch Monitor|Electronics|       5|  19287.21|           0|   Net Banking|Processing|  NULL|
| O000032|2026-08-05|     C02267|Customer_02267|Hyderabad| South|      P001|     Laptop Pro|Electronics|       3|  67819.64|           5|   Credit Card|Processing|  NULL|
| O000033|2026-08-07|     C04595|Customer_04595|Hyderabad| South|      P002| Wireless Mouse|Accessories|       1|   1606.81|           0|           COD| Delivered|     4|
| O000039|2026-10-25|     C02175|Customer_02175|Hyderabad| South|      P002| Wireless Mouse|Accessories|       5|    1484.3|          10|   Net Banking|   Shipped|  NULL|
| O000054|2026-08-25|     C01489|Customer_01489|Hyderabad| South|      P005|   Office Chair|  Furniture|       4|   8751.39|          15|    Debit Card| Delivered|     4|
| O000062|2026-07-14|     C02756|Customer_02756|Hyderabad| South|      P008|     Headphones|Accessories|       3|   3321.83|           5|    Debit Card|Processing|  NULL|
| O000063|2026-05-22|     C04554|Customer_04554|Hyderabad| South|      P009|    Smart Watch|Electronics|       2|  11204.38|          10|   Net Banking| Delivered|     4|
| O000073|2026-08-29|     C02386|Customer_02386|Hyderabad| South|      P004|27 Inch Monitor|Electronics|       3|  18596.03|          15|           UPI|   Shipped|  NULL|
| O000079|2026-07-26|     C04216|Customer_04216|Hyderabad| South|      P011|        Printer|Electronics|       5|  15902.66|           0|   Credit Card| Delivered|     4|
| O000087|2026-09-27|     C03744|Customer_03744|Hyderabad| South|      P012|      Bookshelf|  Furniture|       2|   7391.97|           0|           UPI| Delivered|     4|
| O000094|2026-07-22|     C02249|Customer_02249|Hyderabad| South|      P010|     Web Camera|Accessories|       1|   4475.93|          15|    Debit Card|Processing|  NULL|
| O000096|2026-06-08|     C03612|Customer_03612|Hyderabad| South|      P010|     Web Camera|Accessories|       3|   4356.15|           0|    Debit Card| Delivered|     5|
| O000121|2026-07-22|     C04910|Customer_04910|Hyderabad| South|      P001|     Laptop Pro|Electronics|       2|  62934.76|           5|   Credit Card|Processing|  NULL|
| O000132|2026-09-16|     C01414|Customer_01414|Hyderabad| South|      P004|27 Inch Monitor|Electronics|       4|  19414.04|          20|           COD|   Shipped|  NULL|
| O000138|2026-03-26|     C03586|Customer_03586|Hyderabad| South|      P007|         Tablet|Electronics|       3|  28790.11|           5|   Net Banking|   Shipped|  NULL|
| O000144|2026-01-03|     C00650|Customer_00650|Hyderabad| South|      P005|   Office Chair|  Furniture|       2|   9482.35|          20|           COD| Delivered|     3|
| O000148|2026-07-11|     C02078|Customer_02078|Hyderabad| South|      P006|     Study Desk|  Furniture|       1|  13652.36|           0|           COD|Processing|  NULL|
| O000150|2026-02-02|     C03750|Customer_03750|Hyderabad| South|      P005|   Office Chair|  Furniture|       2|   8343.08|           5|           UPI| Delivered|     5|
| O000151|2026-08-31|     C02076|Customer_02076|Hyderabad| South|      P011|        Printer|Electronics|       2|  15452.44|           0|    Debit Card| Delivered|     4|
+--------+----------+-----------+--------------+---------+------+----------+---------------+-----------+--------+----------+------------+--------------+----------+------+
only showing top 20 rows
+--------+----------+-----------+--------------+---------+------+----------+-------------------+-----------+--------+----------+------------+--------------+----------+------+
|order_id|order_date|customer_id| customer_name|     city|region|product_id|       product_name|   category|quantity|unit_price|discount_pct|payment_method|    status|rating|
+--------+----------+-----------+--------------+---------+------+----------+-------------------+-----------+--------+----------+------------+--------------+----------+------+
| O000008|2026-01-29|     C01877|Customer_01877|Hyderabad| South|      P006|         Study Desk|  Furniture|       4|  13479.74|           5|           COD| Cancelled|  NULL|
| O000010|2026-07-05|     C01797|Customer_01797|  Chennai| South|      P009|        Smart Watch|Electronics|       4|  11214.55|           0|           UPI| Delivered|     5|
| O000011|2026-02-02|     C03153|Customer_03153|    Delhi| North|      P010|         Web Camera|Accessories|       4|   4219.56|          20|           UPI|   Shipped|  NULL|
| O000014|2026-03-24|     C04419|Customer_04419|  Lucknow| North|      P001|         Laptop Pro|Electronics|       5|  63171.22|           0|           UPI| Cancelled|  NULL|
| O000015|2026-06-07|     C01962|Customer_01962|Hyderabad| South|      P004|    27 Inch Monitor|Electronics|       5|  19287.21|           0|   Net Banking|Processing|  NULL|
| O000016|2026-09-30|     C01031|Customer_01031|  Chennai| South|      P011|            Printer|Electronics|       4|  17143.93|           0|    Debit Card| Delivered|     5|
| O000019|2026-05-02|     C02282|Customer_02282|   Jaipur| North|      P004|    27 Inch Monitor|Electronics|       5|  16941.06|          15|   Credit Card|Processing|  NULL|
| O000020|2026-04-08|     C00773|Customer_00773|Bangalore| South|      P011|            Printer|Electronics|       4|   15627.0|          10|   Net Banking| Cancelled|  NULL|
| O000022|2026-05-23|     C03790|Customer_03790|   Mumbai|  West|      P002|     Wireless Mouse|Accessories|       4|   1573.93|          20|           UPI| Delivered|     1|
| O000023|2026-05-02|     C01363|Customer_01363|    Delhi| North|      P008|         Headphones|Accessories|       4|    3339.7|          10|          NULL| Delivered|     4|
| O000024|2026-05-27|     C03466|Customer_03466|  Lucknow| North|      P011|            Printer|Electronics|       4|  15116.28|           5|   Credit Card|  Returned|  NULL|
| O000028|2026-08-23|     C02591|Customer_02591|Bangalore| South|      P001|         Laptop Pro|Electronics|       4|  66260.06|           0|           UPI| Delivered|     3|
| O000038|2026-05-23|     C02877|Customer_02877|  Lucknow| North|      P007|             Tablet|Electronics|       5|  27243.55|           0|           UPI| Cancelled|  NULL|
| O000039|2026-10-25|     C02175|Customer_02175|Hyderabad| South|      P002|     Wireless Mouse|Accessories|       5|    1484.3|          10|   Net Banking|   Shipped|  NULL|
| O000042|2026-10-11|     C01043|Customer_01043|   Mumbai|  West|      P007|             Tablet|Electronics|       4|  28794.38|           0|           COD| Delivered|     3|
| O000043|2026-05-27|     C01722|Customer_01722|    Delhi| North|      P010|         Web Camera|Accessories|       5|   4303.96|          15|   Net Banking| Delivered|     2|
| O000044|2026-02-13|     C02325|Customer_02325|  Lucknow| North|      P011|            Printer|Electronics|       5|  15578.08|           5|    Debit Card| Delivered|  NULL|
| O000045|2026-05-06|     C03893|Customer_03893|  Kolkata|  East|      P002|     Wireless Mouse|Accessories|       4|   1479.47|           5|   Net Banking| Delivered|     1|
| O000046|2026-02-24|     C03483|Customer_03483|   Mumbai|  West|      P003|Mechanical Keyboard|Accessories|       5|   4474.48|          20|   Credit Card| Cancelled|  NULL|
| O000047|2026-03-10|     C03807|Customer_03807|  Lucknow| North|      P009|        Smart Watch|Electronics|       5|  11649.21|          15|           COD|Processing|  NULL|
+--------+----------+-----------+--------------+---------+------+----------+-------------------+-----------+--------+----------+------------+--------------+----------+------+
only showing top 20 rows
+--------+----------+-----------+--------------+---------+------+----------+------------+-----------+--------+----------+------------+--------------+----------+------+
|order_id|order_date|customer_id| customer_name|     city|region|product_id|product_name|   category|quantity|unit_price|discount_pct|payment_method|    status|rating|
+--------+----------+-----------+--------------+---------+------+----------+------------+-----------+--------+----------+------------+--------------+----------+------+
| O000005|2026-10-23|     C01576|Customer_01576|Bangalore| South|      P001|  Laptop Pro|Electronics|       2|  67839.91|           0|   Credit Card| Cancelled|  NULL|
| O000007|2026-05-06|     C01339|Customer_01339|   Jaipur| North|      P007|      Tablet|Electronics|       3|  30193.06|          20|   Credit Card|   Shipped|  NULL|

In [ ]:
from pyspark.sql.functions import col

# 11. Find Electronics transactions from Hyderabad
df.filter((col("category") == "Electronics") & (col("city") == "Hyderabad")).show()

# 12. Find Delivered transactions from the South region
df.filter((col("status") == "Delivered") & (col("region") == "South")).show()

# 13. Find orders having quantity greater than 2 and unit price greater than 10,000
df.filter((col("quantity") > 2) & (col("unit_price") > 10000)).show()

# 14. Find transactions from either Mumbai or Pune
df.filter(col("city").isin(["Mumbai", "Pune"])).show()

# 15. Find transactions that are not Cancelled
df.filter(col("status") != "Cancelled").show()

# 16. Find Furniture products costing more than 8,000
df.filter((col("category") == "Furniture") & (col("unit_price") > 8000)).show()

# 17. Find Accessories products with quantity greater than 3
df.filter((col("category") == "Accessories") & (col("quantity") > 3)).show()

+--------+----------+-----------+--------------+---------+------+----------+---------------+-----------+--------+----------+------------+--------------+----------+------+
|order_id|order_date|customer_id| customer_name|     city|region|product_id|   product_name|   category|quantity|unit_price|discount_pct|payment_method|    status|rating|
+--------+----------+-----------+--------------+---------+------+----------+---------------+-----------+--------+----------+------------+--------------+----------+------+
| O000015|2026-06-07|     C01962|Customer_01962|Hyderabad| South|      P004|27 Inch Monitor|Electronics|       5|  19287.21|           0|   Net Banking|Processing|  NULL|
| O000032|2026-08-05|     C02267|Customer_02267|Hyderabad| South|      P001|     Laptop Pro|Electronics|       3|  67819.64|           5|   Credit Card|Processing|  NULL|
| O000063|2026-05-22|     C04554|Customer_04554|Hyderabad| South|      P009|    Smart Watch|Electronics|       2|  11204.38|          10|   Net Banking| Delivered|     4|
| O000073|2026-08-29|     C02386|Customer_02386|Hyderabad| South|      P004|27 Inch Monitor|Electronics|       3|  18596.03|          15|           UPI|   Shipped|  NULL|
| O000079|2026-07-26|     C04216|Customer_04216|Hyderabad| South|      P011|        Printer|Electronics|       5|  15902.66|           0|   Credit Card| Delivered|     4|
| O000121|2026-07-22|     C04910|Customer_04910|Hyderabad| South|      P001|     Laptop Pro|Electronics|       2|  62934.76|           5|   Credit Card|Processing|  NULL|
| O000132|2026-09-16|     C01414|Customer_01414|Hyderabad| South|      P004|27 Inch Monitor|Electronics|       4|  19414.04|          20|           COD|   Shipped|  NULL|
| O000138|2026-03-26|     C03586|Customer_03586|Hyderabad| South|      P007|         Tablet|Electronics|       3|  28790.11|           5|   Net Banking|   Shipped|  NULL|
| O000151|2026-08-31|     C02076|Customer_02076|Hyderabad| South|      P011|        Printer|Electronics|       2|  15452.44|           0|    Debit Card| Delivered|     4|
| O000194|2026-07-04|     C01936|Customer_01936|Hyderabad| South|      P011|        Printer|Electronics|       1|  15911.41|           0|   Net Banking|   Shipped|  NULL|
| O000225|2026-07-23|     C02674|Customer_02674|Hyderabad| South|      P011|        Printer|Electronics|       3|  16725.88|          15|   Net Banking| Delivered|     2|
| O000262|2026-07-10|     C01356|Customer_01356|Hyderabad| South|      P007|         Tablet|Electronics|       3|  29012.43|           5|   Net Banking|   Shipped|  NULL|
| O000278|2026-04-27|     C04169|Customer_04169|Hyderabad| South|      P001|     Laptop Pro|Electronics|       1|  62343.34|          15|    Debit Card| Delivered|     1|
| O000283|2026-01-04|     C03360|Customer_03360|Hyderabad| South|      P004|27 Inch Monitor|Electronics|       5|   17557.7|           0|    Debit Card| Delivered|     3|
| O000296|2026-05-08|     C04454|Customer_04454|Hyderabad| South|      P007|         Tablet|Electronics|       3|  27908.99|          15|    Debit Card| Cancelled|  NULL|
| O000347|2026-01-25|     C00886|Customer_00886|Hyderabad| South|      P001|     Laptop Pro|Electronics|       1|  64134.47|          10|           UPI| Delivered|     1|
| O000376|2026-06-10|     C04524|Customer_04524|Hyderabad| South|      P001|     Laptop Pro|Electronics|       3|  61912.11|          15|   Credit Card| Cancelled|  NULL|
| O000401|2026-08-29|     C03725|Customer_03725|Hyderabad| South|      P001|     Laptop Pro|Electronics|       3|  60873.54|          20|    Debit Card|Processing|  NULL|
| O000432|2026-08-24|     C02586|Customer_02586|Hyderabad| South|      P001|     Laptop Pro|Electronics|       2|  63746.05|           0|    Debit Card| Delivered|     3|
| O000448|2026-09-02|     C02455|Customer_02455|Hyderabad| South|      P007|         Tablet|Electronics|       3|  28434.58|           0|           COD| Delivered|     4|
+--------+----------+-----------+--------------+---------+------+----------+---------------+-----------+--------+----------+------------+--------------+----------+------+
only showing top 20 rows
+--------+----------+-----------+--------------+---------+------+----------+-------------------+-----------+--------+----------+------------+--------------+---------+------+
|order_id|order_date|customer_id| customer_name|     city|region|product_id|       product_name|   category|quantity|unit_price|discount_pct|payment_method|   status|rating|
+--------+----------+-----------+--------------+---------+------+----------+-------------------+-----------+--------+----------+------------+--------------+---------+------+
| O000010|2026-07-05|     C01797|Customer_01797|  Chennai| South|      P009|        Smart Watch|Electronics|       4|  11214.55|           0|           UPI|Delivered|     5|
| O000016|2026-09-30|     C01031|Customer_01031|  Chennai| South|      P011|            Printer|Electronics|       4|  17143.93|           0|    Debit Card|Delivered|     5|
| O000028|2026-08-23|     C02591|Customer_02591|Bangalore| South|      P001|         Laptop Pro|Electronics|       4|  66260.06|           0|           UPI|Delivered|     3|
| O000033|2026-08-07|     C04595|Customer_04595|Hyderabad| South|      P002|     Wireless Mouse|Accessories|       1|   1606.81|           0|           COD|Delivered|     4|
| O000036|2026-07-31|     C00204|Customer_00204|  Chennai| South|      P012|          Bookshelf|  Furniture|       3|   7838.86|          10|   Credit Card|Delivered|     1|
| O000053|2026-03-26|     C03829|Customer_03829|  Chennai| South|      P010|         Web Camera|Accessories|       5|   3882.12|          10|           COD|Delivered|     2|
| O000054|2026-08-25|     C01489|Customer_01489|Hyderabad| South|      P005|       Office Chair|  Furniture|       4|   8751.39|          15|    Debit Card|Delivered|     4|
| O000063|2026-05-22|     C04554|Customer_04554|Hyderabad| South|      P009|        Smart Watch|Electronics|       2|  11204.38|          10|   Net Banking|Delivered|     4|
| O000070|2026-01-28|     C01243|Customer_01243|  Chennai| South|      P010|         Web Camera|Accessories|       3|   3921.24|           5|           UPI|Delivered|     5|
| O000074|2026-04-12|     C03483|Customer_03483|Bangalore| South|      P009|        Smart Watch|Electronics|       2|  12283.46|           5|   Credit Card|Delivered|     5|
| O000075|2026-05-28|     C03598|Customer_03598|Bangalore| South|      P008|         Headphones|Accessories|       3|   3611.85|           5|           COD|Delivered|     4|
| O000077|2026-08-15|     C02279|Customer_02279|  Chennai| South|      P010|         Web Camera|Accessories|       4|   4290.58|          15|           UPI|Delivered|     1|
| O000079|2026-07-26|     C04216|Customer_04216|Hyderabad| South|      P011|            Printer|Electronics|       5|  15902.66|           0|   Credit Card|Delivered|     4|
| O000087|2026-09-27|     C03744|Customer_03744|Hyderabad| South|      P012|          Bookshelf|  Furniture|       2|   7391.97|           0|           UPI|Delivered|     4|
| O000096|2026-06-08|     C03612|Customer_03612|Hyderabad| South|      P010|         Web Camera|Accessories|       3|   4356.15|           0|    Debit Card|Delivered|     5|
| O000098|2026-02-28|     C03837|Customer_03837|Bangalore| South|      P003|Mechanical Keyboard|Accessories|       2|    4759.3|          10|           COD|Delivered|  NULL|
| O000102|2026-08-03|     C04812|Customer_04812|  Chennai| South|      P007|             Tablet|Electronics|       1|  29494.95|          10|    Debit Card|Delivered|     2|
| O000107|2026-05-16|     C00430|Customer_00430|  Chennai| South|      P012|          Bookshelf|  Furniture|       4|    7531.3|           0|   Net Banking|Delivered|     4|
| O000126|2026-06-20|     C01378|Customer_01378|Bangalore| South|      P009|        Smart Watch|Electronics|       1|  12058.76|           5|    Debit Card|Delivered|     2|
| O000127|2026-05-01|     C00843|Customer_00843|  Chennai| South|      P005|       Office Chair|  Furniture|       2|   8529.84|           0|           UPI|Delivered|     5|
+--------+----------+-----------+--------------+---------+------+----------+-------------------+-----------+--------+----------+------------+--------------+---------+------+
only showing top 20 rows
+--------+----------+-----------+--------------+---------+------+----------+---------------+-----------+--------+----------+------------+--------------+----------+------+
|order_id|order_date|customer_id| customer_name|     city|region|product_id|   product_name|   category|quantity|unit_price|discount_pct|payment_method|    status|rating|
+--------+----------+-----------+--------------+---------+------+----------+---------------+-----------+--------+----------+------------+--------------+----------+------+
| O000006|2026-08-21|     C02989|Customer_02989|  Chennai| South|      P006|     Study Desk|  Furniture|       3|   13349.3|           5|           UPI|   Shipped|  NULL|
| O000007|2026-05-06|     C01339|Customer_01339|   Jaipur| North|      P007|         Tablet|Electronics|       3|  30193.06|          20|   Credit Card|   Shipped|  NULL|
| O000008|2026-01-29|     C01877|Customer_01877|Hyderabad| South|      P006|     Study Desk|  Furniture|       4|  13479.74|           5|           COD| Cancelled|  NULL|
| O000010|2026-07-05|     C01797|Customer_01797|  Chennai| South|      P009|    Smart Watch|Electronics|       4|  11214.55|           0|           UPI| Delivered|     5|
| O000014|2026-03-24|     C04419|Customer_04419|  Lucknow| North|      P001|     Laptop Pro|Electronics|       5|  63171.22|           0|           UPI| Cancelled|  NULL|
| O000015|2026-06-07|     C01962|Customer_01962|Hyderabad| South|      P004|27 Inch Monitor|Electronics|       5|  19287.21|           0|   Net Banking|Processing|  NULL|
| O000016|2026-09-30|     C01031|Customer_01031|  Chennai| South|      P011|        Printer|Electronics|       4|  17143.93|           0|    Debit Card| Delivered|     5|
| O000017|2026-04-13|     C02554|Customer_02554|    Delhi| North|      P011|        Printer|Electronics|       3|  15841.54|          20|   Net Banking| Delivered|     5|
| O000019|2026-05-02|     C02282|Customer_02282|   Jaipur| North|      P004|27 Inch Monitor|Electronics|       5|  16941.06|          15|   Credit Card|Processing|  NULL|
| O000020|2026-04-08|     C00773|Customer_00773|Bangalore| South|      P011|        Printer|Electronics|       4|   15627.0|          10|   Net Banking| Cancelled|  NULL|
| O000024|2026-05-27|     C03466|Customer_03466|  Lucknow| North|      P011|        Printer|Electronics|       4|  15116.28|           5|   Credit Card|  Returned|  NULL|
| O000027|2026-08-03|     C04782|Customer_04782|  Kolkata|  East|      P009|    Smart Watch|Electronics|       3|  12834.64|           5|    Debit Card| Delivered|     3|
| O000028|2026-08-23|     C02591|Customer_02591|Bangalore| South|      P001|     Laptop Pro|Electronics|       4|  66260.06|           0|           UPI| Delivered|     3|
| O000032|2026-08-05|     C02267|Customer_02267|Hyderabad| South|      P001|     Laptop Pro|Electronics|       3|  67819.64|           5|   Credit Card|Processing|  NULL|
| O000038|2026-05-23|     C02877|Customer_02877|  Lucknow| North|      P007|         Tablet|Electronics|       5|  27243.55|           0|           UPI| Cancelled|  NULL|
| O000042|2026-10-11|     C01043|Customer_01043|   Mumbai|  West|      P007|         Tablet|Electronics|       4|  28794.38|           0|           COD| Delivered|     3|
| O000044|2026-02-13|     C02325|Customer_02325|  Lucknow| North|      P011|        Printer|Electronics|       5|  15578.08|           5|    Debit Card| Delivered|  NULL|
| O000047|2026-03-10|     C03807|Customer_03807|  Lucknow| North|      P009|    Smart Watch|Electronics|       5|  11649.21|          15|           COD|Processing|  NULL|
| O000052|2026-10-03|     C04474|Customer_04474|  Kolkata|  East|      P004|27 Inch Monitor|Electronics|       4|  17191.93|          10|   Net Banking| Delivered|     4|
| O000055|2026-05-10|     C00671|Customer_00671|   Jaipur| North|      P001|     Laptop Pro|Electronics|       5|  60341.69|          10|   Credit Card|   Shipped|  NULL|
+--------+----------+-----------+--------------+---------+------+----------+---------------+-----------+--------+----------+------------+--------------+----------+------+
only showing top 20 rows
+--------+----------+-----------+--------------+------+------+----------+-------------------+-----------+--------+----------+------------+--------------+----------+------+
|order_id|order_date|customer_id| customer_name|  city|region|product_id|       product_name|   category|quantity|unit_price|discount_pct|payment_method|    status|rating|
+--------+----------+-----------+--------------+------+------+----------+-------------------+-----------+--------+----------+------------+--------------+----------+------+
| O000001|2026-02-27|     C00205|Customer_00205|  Pune|  West|      P004|    27 Inch Monitor|Electronics|       2|  16961.87|           0|           COD| Delivered|  NULL|
| O000022|2026-05-23|     C03790|Customer_03790|Mumbai|  West|      P002|     Wireless Mouse|Accessories|       4|   1573.93|          20|           UPI| Delivered|     1|
| O000031|2026-05-25|     C04955|Customer_04955|Mumbai|  West|      P012|          Bookshelf|  Furniture|       3|   7144.32|           5|           COD| Delivered|     1|
| O000034|2026-03-07|     C00343|Customer_00343|  Pune|  West|      P006|         Study Desk|  Furniture|       1|  14893.59|           5|   Credit Card|   Shipped|  NULL|
| O000037|2026-08-29|     C01823|Customer_01823|Mumbai|  West|      P008|         Headphones|Accessories|       3|   3390.91|           5|   Credit Card| Delivered|     1|
| O000040|2026-07-17|     C04724|Customer_04724|Mumbai|  West|      P005|       Office Chair|  Furniture|       1|   9300.65|           0|           COD| Cancelled|  NULL|
| O000042|2026-10-11|     C01043|Customer_01043|Mumbai|  West|      P007|             Tablet|Electronics|       4|  28794.38|           0|           COD| Delivered|     3|
| O000046|2026-02-24|     C03483|Customer_03483|Mumbai|  West|      P003|Mechanical Keyboard|Accessories|       5|   4474.48|          20|   Credit Card| Cancelled|  NULL|
| O000056|2026-01-21|     C00255|Customer_00255|Mumbai|  West|      P004|    27 Inch Monitor|Electronics|       1|  18349.45|           5|   Credit Card| Delivered|     4|
| O000059|2026-05-05|     C00835|Customer_00835|  Pune|  West|      P011|            Printer|Electronics|       5|  16782.15|           0|    Debit Card| Delivered|     3|
| O000067|2026-05-25|     C00824|Customer_00824|Mumbai|  West|      P005|       Office Chair|  Furniture|       2|   8799.67|           5|           UPI|   Shipped|  NULL|
| O000072|2026-04-17|     C01729|Customer_01729|  Pune|  West|      P011|            Printer|Electronics|       1|  15122.07|           0|          NULL| Delivered|     5|
| O000076|2026-06-15|     C04946|Customer_04946|  Pune|  West|      P001|         Laptop Pro|Electronics|       1|  62180.81|           0|    Debit Card| Delivered|     5|
| O000080|2026-01-27|     C01668|Customer_01668|  Pune|  West|      P009|        Smart Watch|Electronics|       2|  12821.13|          15|   Net Banking| Delivered|     2|
| O000082|2026-05-30|     C04169|Customer_04169|  Pune|  West|      P007|             Tablet|Electronics|       4|   30151.5|           5|   Net Banking| Delivered|     5|
| O000083|2026-03-11|     C00572|Customer_00572|  Pune|  West|      P007|             Tablet|Electronics|       3|  29945.43|          20|    Debit Card|Processing|  NULL|
| O000085|2026-08-22|     C02637|Customer_02637|Mumbai|  West|      P012|          Bookshelf|  Furniture|       2|   7586.16|           5|   Net Banking| Delivered|     4|
| O000090|2026-08-09|     C01193|Customer_01193|Mumbai|  West|      P009|        Smart Watch|Electronics|       4|  12126.58|           0|   Credit Card| Delivered|     2|
| O000095|2026-06-30|     C01795|Customer_01795|Mumbai|  West|      P010|         Web Camera|Accessories|       3|   4319.46|           0|           UPI| Cancelled|  NULL|
| O000101|2026-01-24|     C00305|Customer_00305|  Pune|  West|      P008|         Headphones|Accessories|       1|   3274.43|          20|   Credit Card| Delivered|     5|
+--------+----------+-----------+--------------+------+------+----------+-------------------+-----------+--------+----------+------------+--------------+----------+------+
only showing top 20 rows
+--------+----------+-----------+--------------+---------+------+----------+-------------------+-----------+--------+----------+------------+--------------+----------+------+
|order_id|order_date|customer_id| customer_name|     city|region|product_id|       product_name|   category|quantity|unit_price|discount_pct|payment_method|    status|rating|
+--------+----------+-----------+--------------+---------+------+----------+-------------------+-----------+--------+----------+------------+--------------+----------+------+
| O000001|2026-02-27|     C00205|Customer_00205|     Pune|  West|      P004|    27 Inch Monitor|Electronics|       2|  16961.87|           0|           COD| Delivered|  NULL|
| O000002|2026-04-22|     C01906|Customer_01906|  Lucknow| North|      P010|         Web Camera|Accessories|       1|   4241.16|          20|   Net Banking| Delivered|     1|
| O000003|2026-03-23|     C03463|Customer_03463|Ahmedabad|  West|      P005|       Office Chair|  Furniture|       2|   8590.05|          10|           UPI| Delivered|     5|
| O000004|2026-05-16|     C00356|Customer_00356|   Jaipur| North|      P009|        Smart Watch|Electronics|       1|  12908.38|          10|           UPI| Delivered|     3|
| O000006|2026-08-21|     C02989|Customer_02989|  Chennai| South|      P006|         Study Desk|  Furniture|       3|   13349.3|           5|           UPI|   Shipped|  NULL|
| O000007|2026-05-06|     C01339|Customer_01339|   Jaipur| North|      P007|             Tablet|Electronics|       3|  30193.06|          20|   Credit Card|   Shipped|  NULL|
| O000009|2026-09-13|     C03242|Customer_03242|   Jaipur| North|      P003|Mechanical Keyboard|Accessories|       3|   4240.53|          20|           COD| Delivered|     4|
| O000010|2026-07-05|     C01797|Customer_01797|  Chennai| South|      P009|        Smart Watch|Electronics|       4|  11214.55|           0|           UPI| Delivered|     5|
| O000011|2026-02-02|     C03153|Customer_03153|    Delhi| North|      P010|         Web Camera|Accessories|       4|   4219.56|          20|           UPI|   Shipped|  NULL|
| O000012|2026-10-02|     C02186|Customer_02186|Ahmedabad|  West|      P002|     Wireless Mouse|Accessories|       3|   1484.34|          15|           UPI|  Returned|  NULL|
| O000013|2026-05-15|     C04101|Customer_04101|  Chennai| South|      P009|        Smart Watch|Electronics|       1|   12711.4|           5|           COD|   Shipped|  NULL|
| O000015|2026-06-07|     C01962|Customer_01962|Hyderabad| South|      P004|    27 Inch Monitor|Electronics|       5|  19287.21|           0|   Net Banking|Processing|  NULL|
| O000016|2026-09-30|     C01031|Customer_01031|  Chennai| South|      P011|            Printer|Electronics|       4|  17143.93|           0|    Debit Card| Delivered|     5|
| O000017|2026-04-13|     C02554|Customer_02554|    Delhi| North|      P011|            Printer|Electronics|       3|  15841.54|          20|   Net Banking| Delivered|     5|
| O000018|2026-10-11|     C01886|Customer_01886|  Kolkata|  East|      P004|    27 Inch Monitor|Electronics|       1|  16764.46|           0|   Credit Card| Delivered|     5|
| O000019|2026-05-02|     C02282|Customer_02282|   Jaipur| North|      P004|    27 Inch Monitor|Electronics|       5|  16941.06|          15|   Credit Card|Processing|  NULL|

In [ ]:
# 18. Select only order_id, customer_name, product_name, unit_price
df.select("order_id", "customer_name", "product_name", "unit_price").show()

# 19 & 20. Rename columns (unit_price -> price, customer_name -> customer)
df_renamed = df.withColumnRenamed("unit_price", "price") \
               .withColumnRenamed("customer_name", "customer")

# 21 & 22. Drop columns
df_dropped_rating = df.drop("rating")
df_new_dropped = df.drop("customer_name", "rating", "payment_method")

# 23. Add gross_amount (quantity * unit_price)
df = df.withColumn("gross_amount", col("quantity") * col("unit_price"))

# 24. Add discount_amount (gross_amount * discount_pct / 100)
df = df.withColumn("discount_amount", col("gross_amount") * (col("discount_pct") / 100))

# 25. Add final_amount (gross_amount - discount_amount)
df = df.withColumn("final_amount", col("gross_amount") - col("discount_amount"))

# 26. Add constant column country = 'India'
from pyspark.sql.functions import lit
df = df.withColumn("country", lit("India"))

# 27. Add high_value (Yes if final_amount >= 50000 else No)
from pyspark.sql.functions import when
df = df.withColumn("high_value", when(col("final_amount") >= 50000, "Yes").otherwise("No"))

+--------+--------------+-------------------+----------+
|order_id| customer_name|       product_name|unit_price|
+--------+--------------+-------------------+----------+
| O000001|Customer_00205|    27 Inch Monitor|  16961.87|
| O000002|Customer_01906|         Web Camera|   4241.16|
| O000003|Customer_03463|       Office Chair|   8590.05|
| O000004|Customer_00356|        Smart Watch|  12908.38|
| O000005|Customer_01576|         Laptop Pro|  67839.91|
| O000006|Customer_02989|         Study Desk|   13349.3|
| O000007|Customer_01339|             Tablet|  30193.06|
| O000008|Customer_01877|         Study Desk|  13479.74|
| O000009|Customer_03242|Mechanical Keyboard|   4240.53|
| O000010|Customer_01797|        Smart Watch|  11214.55|
| O000011|Customer_03153|         Web Camera|   4219.56|
| O000012|Customer_02186|     Wireless Mouse|   1484.34|
| O000013|Customer_04101|        Smart Watch|   12711.4|
| O000014|Customer_04419|         Laptop Pro|  63171.22|
| O000015|Customer_01962|    27 Inch Monitor|  19287.21|
| O000016|Customer_01031|            Printer|  17143.93|
| O000017|Customer_02554|            Printer|  15841.54|
| O000018|Customer_01886|    27 Inch Monitor|  16764.46|
| O000019|Customer_02282|    27 Inch Monitor|  16941.06|
| O000020|Customer_00773|            Printer|   15627.0|
+--------+--------------+-------------------+----------+
only showing top 20 rows

In [ ]:
# 28. Create order_size (High, Medium, Low)
df = df.withColumn("order_size",
    when(col("final_amount") > 50000, "High")
    .when(col("final_amount") >= 15000, "Medium")
    .otherwise("Low")
)

# 29. Create quantity_type (Bulk if quantity >= 4 else Regular)
df = df.withColumn("quantity_type", when(col("quantity") >= 4, "Bulk").otherwise("Regular"))

# 30. Create delivery-status categories if needed based on your status values
df = df.withColumn("delivery_category",
    when(col("status") == "Delivered", "Completed")
    .when(col("status").isin(["Cancelled", "Returned"]), "Failed")
    .otherwise("In Progress")
)

In [ ]:
# 31. Sort by unit price highest to lowest
df.orderBy(col("unit_price").desc()).show()

# 33. Sort alphabetically by city
df.orderBy(col("city").asc()).show()

# 35. Display 10 highest-value transactions
df.orderBy(col("final_amount").desc()).limit(10).show()

# 36. Display all unique cities[cite: 6]
df.select("city").distinct().show()

# 40. Count unique customers[cite: 6]
df.select("customer_id").distinct().count()

# 42-48. Aggregations
from pyspark.sql.functions import sum, avg, min, max
df.select(
    sum("quantity").alias("total_quantity"),
    sum("gross_amount").alias("total_gross_sales"),
    avg("unit_price").alias("avg_unit_price"),
    max("unit_price").alias("max_unit_price"),
    min("unit_price").alias("min_unit_price"),
    sum("discount_amount").alias("total_discount"),
    sum("final_amount").alias("total_final_sales")
).show()

+--------+----------+-----------+--------------+---------+------+----------+------------+-----------+--------+----------+------------+--------------+----------+------+------------------+------------------+------------------+-------+----------+----------+-------------+-----------------+
|order_id|order_date|customer_id| customer_name|     city|region|product_id|product_name|   category|quantity|unit_price|discount_pct|payment_method|    status|rating|      gross_amount|   discount_amount|      final_amount|country|high_value|order_size|quantity_type|delivery_category|
+--------+----------+-----------+--------------+---------+------+----------+------------+-----------+--------+----------+------------+--------------+----------+------+------------------+------------------+------------------+-------+----------+----------+-------------+-----------------+
| O016427|2026-01-20|     C01275|Customer_01275|Ahmedabad|  West|      P001|  Laptop Pro|Electronics|       1|  70199.47|           0|           COD| Cancelled|  NULL|          70199.47|               0.0|          70199.47|  India|       Yes|      High|      Regular|           Failed|
| O016344|2026-04-08|     C01455|Customer_01455|  Chennai| South|      P001|  Laptop Pro|Electronics|       1|  70199.37|           5|           COD|Processing|  NULL|          70199.37|         3509.9685| 66689.40149999999|  India|       Yes|      High|      Regular|      In Progress|
| O049413|2026-05-06|     C02982|Customer_02982|   Jaipur| North|      P001|  Laptop Pro|Electronics|       4|  70198.94|          10|   Credit Card| Delivered|     5|         280795.76|         28079.576|        252716.184|  India|       Yes|      High|         Bulk|        Completed|
| O045993|2026-03-28|     C04122|Customer_04122|Hyderabad| South|      P001|  Laptop Pro|Electronics|       4|  70198.65|          20|   Credit Card|Processing|  NULL|          280794.6|          56158.92|         224635.68|  India|       Yes|      High|         Bulk|      In Progress|
| O021133|2026-10-01|     C03151|Customer_03151|   Jaipur| North|      P001|  Laptop Pro|Electronics|       3|  70197.03|           0|   Net Banking| Delivered|     4|         210591.09|               0.0|         210591.09|  India|       Yes|      High|      Regular|        Completed|
| O032504|2026-01-15|     C04271|Customer_04271|    Delhi| North|      P001|  Laptop Pro|Electronics|       1|  70196.04|           0|           UPI|Processing|  NULL|          70196.04|               0.0|          70196.04|  India|       Yes|      High|      Regular|      In Progress|
| O098623|2026-08-01|     C04557|Customer_04557|    Delhi| North|      P001|  Laptop Pro|Electronics|       5|  70194.23|           5|           UPI|Processing|  NULL|350971.14999999997|        17548.5575|333422.59249999997|  India|       Yes|      High|         Bulk|      In Progress|
| O056905|2026-06-28|     C03305|Customer_03305|Ahmedabad|  West|      P001|  Laptop Pro|Electronics|       3|  70192.81|           5|    Debit Card| Delivered|     3|         210578.43|        10528.9215|       200049.5085|  India|       Yes|      High|      Regular|        Completed|
| O048720|2026-04-02|     C03383|Customer_03383|Ahmedabad|  West|      P001|  Laptop Pro|Electronics|       3|  70188.46|           0|           COD| Delivered|     1|         210565.38|               0.0|         210565.38|  India|       Yes|      High|      Regular|        Completed|
| O018458|2026-04-16|     C03316|Customer_03316|     Pune|  West|      P001|  Laptop Pro|Electronics|       5|  70183.76|           5|    Debit Card| Delivered|     3|          350918.8|          17545.94|         333372.86|  India|       Yes|      High|         Bulk|        Completed|
| O070763|2026-10-10|     C01486|Customer_01486|   Jaipur| North|      P001|  Laptop Pro|Electronics|       5|  70180.14|          20|           COD| Delivered|     5|          350900.7|          70180.14|         280720.56|  India|       Yes|      High|         Bulk|        Completed|
| O080313|2026-09-21|     C04123|Customer_04123|     Pune|  West|      P001|  Laptop Pro|Electronics|       3|  70179.37|           5|           UPI| Delivered|     5|         210538.11|        10526.9055|       200011.2045|  India|       Yes|      High|      Regular|        Completed|
| O049094|2026-01-05|     C04810|Customer_04810|     Pune|  West|      P001|  Laptop Pro|Electronics|       4|  70179.14|           5|    Debit Card| Delivered|     1|         280716.56|14035.828000000001|        266680.732|  India|       Yes|      High|         Bulk|        Completed|
| O080283|2026-07-26|     C01087|Customer_01087|  Chennai| South|      P001|  Laptop Pro|Electronics|       4|  70178.69|           5|   Credit Card| Delivered|     3|         280714.76|14035.738000000001|        266679.022|  India|       Yes|      High|         Bulk|        Completed|
| O011763|2026-03-26|     C00514|Customer_00514|   Jaipur| North|      P001|  Laptop Pro|Electronics|       5|  70178.65|          10|           UPI| Delivered|     3|         350893.25|35089.325000000004|        315803.925|  India|       Yes|      High|         Bulk|        Completed|
| O098357|2026-09-18|     C04979|Customer_04979|  Chennai| South|      P001|  Laptop Pro|Electronics|       3|  70177.98|          15|   Net Banking|   Shipped|  NULL|         210533.94|         31580.091|        178953.849|  India|       Yes|      High|      Regular|      In Progress|
| O030561|2026-05-24|     C01970|Customer_01970|   Jaipur| North|      P001|  Laptop Pro|Electronics|       5|  70177.66|          20|    Debit Card| Delivered|     3|350888.30000000005| 70177.66000000002|         280710.64|  India|       Yes|      High|         Bulk|        Completed|
| O068019|2026-03-30|     C03441|Customer_03441|   Jaipur| North|      P001|  Laptop Pro|Electronics|       4|  70176.31|           0|   Net Banking| Delivered|     4|         280705.24|               0.0|         280705.24|  India|       Yes|      High|         Bulk|        Completed|
| O097533|2026-08-26|     C01899|Customer_01899|Ahmedabad|  West|      P001|  Laptop Pro|Electronics|       5|  70176.03|          10|   Net Banking| Delivered|     1|         350880.15| 35088.01500000001|        315792.135|  India|       Yes|      High|         Bulk|        Completed|
| O019622|2026-05-27|     C00017|Customer_00017|  Lucknow| North|      P001|  Laptop Pro|Electronics|       3|   70174.9|          20|    Debit Card| Delivered|     5|210524.69999999998|          42104.94|168419.75999999998|  India|       Yes|      High|      Regular|        Completed|
+--------+----------+-----------+--------------+---------+------+----------+------------+-----------+--------+----------+------------+--------------+----------+------+------------------+------------------+------------------+-------+----------+----------+-------------+-----------------+
only showing top 20 rows
+--------+----------+-----------+--------------+---------+------+----------+-------------------+-----------+--------+----------+------------+--------------+----------+------+------------------+------------------+------------------+-------+----------+----------+-------------+-----------------+
|order_id|order_date|customer_id| customer_name|     city|region|product_id|       product_name|   category|quantity|unit_price|discount_pct|payment_method|    status|rating|      gross_amount|   discount_amount|      final_amount|country|high_value|order_size|quantity_type|delivery_category|
+--------+----------+-----------+--------------+---------+------+----------+-------------------+-----------+--------+----------+------------+--------------+----------+------+------------------+------------------+------------------+-------+----------+----------+-------------+-----------------+
| O068117|2026-03-23|     C02898|Customer_02898|Ahmedabad|  West|      P001|         Laptop Pro|Electronics|       4|  62766.64|           0|           COD| Delivered|     2|         251066.56|               0.0|         251066.56|  India|       Yes|      High|         Bulk|        Completed|
| O000232|2026-06-18|     C03607|Customer_03607|Ahmedabad|  West|      P007|             Tablet|Electronics|       5|  26369.84|          10|           COD|  Returned|  NULL|          131849.2|13184.920000000002|118664.28000000001|  India|       Yes|      High|         Bulk|           Failed|
| O068315|2026-06-05|     C02252|Customer_02252|Ahmedabad|  West|      P003|Mechanical Keyboard|Accessories|       3|   4588.14|          10|           COD|   Shipped|  NULL|13764.420000000002|1376.4420000000002|12387.978000000001|  India|        No|       Low|      Regular|      In Progress|
| O000393|2026-09-07|     C02711|Customer_02711|Ahmedabad|  West|      P003|Mechanical Keyboard|Accessories|       2|   4212.03|           0|   Credit Card| Delivered|     3|           8424.06|               0.0|           8424.06|  India|        No|       Low|      Regular|        Completed|
| O068127|2026-08-06|     C02113|Customer_02113|Ahmedabad|  West|      P005|       Office Chair|  Furniture|       4|   9378.53|           5|   Credit Card| Delivered|     2|          37514.12|1875.7060000000001|35638.414000000004|  India|        No|    Medium|         Bulk|        Completed|
| O000234|2026-05-24|     C03219|Customer_03219|Ahmedabad|  West|      P002|     Wireless Mouse|Accessories|       5|   1427.95|          20|   Credit Card|   Shipped|  NULL|           7139.75|           1427.95|            5711.8|  India|        No|       Low|         Bulk|      In Progress|
| O067973|2026-08-25|     C02967|Customer_02967|Ahmedabad|  West|      P012|          Bookshelf|  Furniture|       2|   7345.59|          10|   Net Banking|Processing|  NULL|          14691.18|1469.1180000000002|         13222.062|  India|        No|       Low|      Regular|      In Progress|
| O000012|2026-10-02|     C02186|Customer_02186|Ahmedabad|  West|      P002|     Wireless Mouse|Accessories|       3|   1484.34|          15|           UPI|  Returned|  NULL|4453.0199999999995| 667.9529999999999|3785.0669999999996|  India|        No|       Low|      Regular|           Failed|
| O068143|2026-04-11|     C03346|Customer_03346|Ahmedabad|  West|      P003|Mechanical Keyboard|Accessories|       5|   4519.78|          10|    Debit Card| Cancelled|  NULL|22598.899999999998|           2259.89|          20339.01|  India|        No|    Medium|         Bulk|           Failed|
| O000246|2026-02-13|     C01098|Customer_01098|Ahmedabad|  West|      P002|     Wireless Mouse|Accessories|       2|   1453.29|           0|    Debit Card|   Shipped|  NULL|           2906.58|               0.0|           2906.58|  India|        No|       Low|      Regular|      In Progress|
| O067979|2026-04-13|     C03451|Customer_03451|Ahmedabad|  West|      P003|Mechanical Keyboard|Accessories|       3|   4600.92|           5|           COD|Processing|  NULL|          13802.76|           690.138|         13112.622|  India|        No|       Low|      Regular|      In Progress|
| O000029|2026-02-05|     C02002|Customer_02002|Ahmedabad|  West|      P005|       Office Chair|  Furniture|       2|   8910.99|          20|    Debit Card|   Shipped|  NULL|          17821.98|          3564.396|14257.583999999999|  India|        No|       Low|      Regular|      In Progress|
| O068151|2026-07-22|     C00244|Customer_00244|Ahmedabad|  West|      P008|         Headphones|Accessories|       1|   3589.57|          10|           UPI|   Shipped|  NULL|           3589.57|358.95700000000005|3230.6130000000003|  India|        No|       Low|      Regular|      In Progress|
| O000258|2026-09-21|     C02280|Customer_02280|Ahmedabad|  West|      P008|         Headphones|Accessories|       4|   3403.28|           0|           UPI|Processing|  NULL|          13613.12|               0.0|          13613.12|  India|        No|       Low|         Bulk|      In Progress|
| O067983|2026-03-18|     C04563|Customer_04563|Ahmedabad|  West|      P010|         Web Camera|Accessories|       2|   3964.44|           0|          NULL|   Shipped|  NULL|           7928.88|               0.0|           7928.88|  India|        No|       Low|      Regular|      In Progress|
| O000103|2026-07-05|     C00814|Customer_00814|Ahmedabad|  West|      P009|        Smart Watch|Electronics|       3|  11156.26|           5|   Credit Card|  Returned|  NULL|          33468.78|          1673.439|         31795.341|  India|        No|    Medium|      Regular|           Failed|
| O068159|2026-03-04|     C04493|Customer_04493|Ahmedabad|  West|      P001|         Laptop Pro|Electronics|       4|  66726.16|          15|           UPI|   Shipped|  NULL|         266904.64|         40035.696|226868.94400000002|  India|       Yes|      High|         Bulk|      In Progress|
| O000282|2026-05-05|     C03801|Customer_03801|Ahmedabad|  West|      P010|         Web Camera|Accessories|       4|   4534.51|           5|           COD|Processing|  NULL|          18138.04|           906.902|         17231.138|  India|        No|    Medium|         Bulk|      In Progress|
| O068103|2026-04-25|     C02978|Customer_02978|Ahmedabad|  West|      P012|          Bookshelf|  Furniture|       1|   7763.14|           0|   Net Banking| Delivered|     3|           7763.14|               0.0|           7763.14|  India|        No|       Low|      Regular|        Completed|
| O000118|2026-08-03|     C03717|Customer_03717|Ahmedabad|  West|      P003|Mechanical Keyboard|Accessories|       3|   4364.38|          10|           COD|   Shipped|  NULL|          13093.14|          1309.314|         11783.826|  India|        No|       Low|      Regular|      In Progress|
+--------+----------+-----------+--------------+---------+------+----------+-------------------+-----------+--------+----------+------------+--------------+----------+------+------------------+------------------+------------------+-------+----------+----------+-------------+-----------------+
only showing top 20 rows
+--------+----------+-----------+--------------+---------+------+----------+------------+-----------+--------+----------+------------+--------------+----------+------+------------------+---------------+------------------+-------+----------+----------+-------------+-----------------+
|order_id|order_date|customer_id| customer_name|     city|region|product_id|product_name|   category|quantity|unit_price|discount_pct|payment_method|    status|rating|      gross_amount|discount_amount|      final_amount|country|high_value|order_size|quantity_type|delivery_category|
+--------+----------+-----------+--------------+---------+------+----------+------------+-----------+--------+----------+------------+--------------+----------+------+------------------+---------------+------------------+-------+----------+----------+-------------+-----------------+
| O022790|2026-04-13|     C01701|Customer_01701|Ahmedabad|  West|      P001|  Laptop Pro|Electronics|       5|  70166.42|           0|           UPI| Delivered|     4|          350832.1|            0.0|          350832.1|  India|       Yes|      High|         Bulk|        Completed|
| O074430|2026-07-26|     C01250|Customer_01250|Bangalore| South|      P001|  Laptop Pro|Electronics|       5|  70140.46|           0|           COD|   Shipped|  NULL|350702.30000000005|            0.0|350702.30000000005|  India|       Yes|      High|         Bulk|      In Progress|
| O090930|2026-08-25|     C02499|Customer_02499|     Pune|  West|      P001|  Laptop Pro|Electronics|       5|  70130.78|           0|    Debit Card|   Shipped|  NULL|          350653.9|            0.0|          350653.9|  India|       Yes|      High|         Bulk|      In Progress|
| O029764|2026-05-03|     C02930|Customer_02930|Ahmedabad|  West|      P001|  Laptop Pro|Electronics|       5|  70116.35|           0|   Credit Card| Delivered|     5|         350581.75|            0.0|         350581.75|  India|       Yes|      High|         Bulk|        Completed|
| O013170|2026-08-15|     C00171|Customer_00171|     Pune|  West|      P001|  Laptop Pro|Electronics|       5|  70111.36|           0|   Net Banking| Delivered|     1|          350556.8|            0.0|          350556.8|  India|       Yes|      High|         Bulk|        Completed|
| O079397|2026-08-25|     C01153|Customer_01153|  Kolkata|  East|      P001|  Laptop Pro|Electronics|       5|   70097.2|           0|           COD| Delivered|     1|          350486.0|            0.0|          350486.0|  India|       Yes|      High|         Bulk|        Completed|
| O072112|2026-05-26|     C00480|Customer_00480|Ahmedabad|  West|      P001|  Laptop Pro|Electronics|       5|  70003.02|           0|           UPI|  Returned|  NULL|350015.10000000003|            0.0|350015.10000000003|  India|       Yes|      High|         Bulk|           Failed|
| O013193|2026-01-10|     C03978|Customer_03978|Ahmedabad|  West|      P001|  Laptop Pro|Electronics|       5|  69969.93|           0|    Debit Card| Delivered|     5|349849.64999999997|            0.0|349849.64999999997|  India|       Yes|      High|         Bulk|        Completed|
| O026081|2026-10-15|     C00745|Customer_00745|  Kolkata|  East|      P001|  Laptop Pro|Electronics|       5|   69962.1|           0|   Net Banking|Processing|  NULL|          349810.5|            0.0|          349810.5|  India|       Yes|      High|         Bulk|      In Progress|
| O056186|2026-03-23|     C03534|Customer_03534|Bangalore| South|      P001|  Laptop Pro|Electronics|       5|  69960.23|           0|           UPI| Delivered|     2|349801.14999999997|            0.0|349801.14999999997|  India|       Yes|      High|         Bulk|        Completed|
+--------+----------+-----------+--------------+---------+------+----------+------------+-----------+--------+----------+------------+--------------+----------+------+------------------+---------------+------------------+-------+----------+----------+-------------+-----------------+

+---------+
|     city|
+---------+
|Bangalore|
|  Lucknow|
|  Chennai|
|   Mumbai|
|Ahmedabad|
|  Kolkata|
|     Pune|
|    Delhi|
|Hyderabad|
|   Jaipur|
+---------+

+--------------+-------------------+------------------+--------------+--------------+--------------------+--------------------+
|total_quantity|  total_gross_sales|    avg_unit_price|max_unit_price|min_unit_price|      total_discount|   total_final_sales|
+--------------+-------------------+------------------+--------------+--------------+--------------------+--------------------+
|        299847|4.572021076219994E9|15249.830077900064|      70199.47|       1380.07|3.3071931457649994E8|4.2413017616434937E9|
+--------------+-------------------+------------------+--------------+--------------+--------------------+--------------------+

In [ ]:
# 49. Count transactions by status
df.groupBy("status").count().show()

# 52. Calculate total sales by region
df.groupBy("region").sum("final_amount").show()

# 62. Find the top 5 cities based on total sales
df.groupBy("city") \
  .sum("final_amount") \
  .withColumnRenamed("sum(final_amount)", "total_sales") \
  .orderBy(col("total_sales").desc()) \
  .limit(5).show()

# 65-67. Date processing (extract year, month, day)
from pyspark.sql.functions import year, month, dayofmonth
df = df.withColumn("year", year("order_date")) \
       .withColumn("month", month("order_date")) \
       .withColumn("day", dayofmonth("order_date"))

# 73-76. Check for missing values
df.filter(col("payment_method").isNull()).show()
print("Missing payment methods count:", df.filter(col("payment_method").isNull()).count())

# 77 & 78. Replace missing values
df = df.na.fill({"payment_method": "Unknown", "rating": 0})

# 79. Drop records having missing payment methods
df = df.dropna(subset=["payment_method"])

+----------+-----+
|    status|count|
+----------+-----+
|  Returned| 5912|
|   Shipped|13950|
|Processing|12115|
| Cancelled| 9927|
| Delivered|58096|
+----------+-----+

+------+--------------------+
|region|   sum(final_amount)|
+------+--------------------+
| South|1.2736728779755006E9|
|  East| 4.188441210040009E8|
|  West|1.2745074508245018E9|
| North|1.2742773118394942E9|
+------+--------------------+

+---------+--------------------+
|     city|         total_sales|
+---------+--------------------+
|     Pune| 4.380059195804999E8|
|Ahmedabad|4.2995853770049965E8|
|Hyderabad| 4.282570748114998E8|
|  Lucknow|4.2674751151249886E8|
|Bangalore|4.2477450649949884E8|
+---------+--------------------+

+--------+----------+-----------+--------------+---------+------+----------+-------------------+-----------+--------+----------+------------+--------------+----------+------+------------------+------------------+------------------+-------+----------+----------+-------------+-----------------+----+-----+---+
|order_id|order_date|customer_id| customer_name|     city|region|product_id|       product_name|   category|quantity|unit_price|discount_pct|payment_method|    status|rating|      gross_amount|   discount_amount|      final_amount|country|high_value|order_size|quantity_type|delivery_category|year|month|day|
+--------+----------+-----------+--------------+---------+------+----------+-------------------+-----------+--------+----------+------------+--------------+----------+------+------------------+------------------+------------------+-------+----------+----------+-------------+-----------------+----+-----+---+
| O000023|2026-05-02|     C01363|Customer_01363|    Delhi| North|      P008|         Headphones|Accessories|       4|    3339.7|          10|          NULL| Delivered|     4|           13358.8|           1335.88|12022.919999999998|  India|        No|       Low|         Bulk|        Completed|2026|    5|  2|
| O000072|2026-04-17|     C01729|Customer_01729|     Pune|  West|      P011|            Printer|Electronics|       1|  15122.07|           0|          NULL| Delivered|     5|          15122.07|               0.0|          15122.07|  India|        No|    Medium|      Regular|        Completed|2026|    4| 17|
| O000106|2026-10-04|     C02054|Customer_02054|  Chennai| South|      P002|     Wireless Mouse|Accessories|       1|   1411.63|          10|          NULL|   Shipped|  NULL|           1411.63|           141.163|          1270.467|  India|        No|       Low|      Regular|      In Progress|2026|   10|  4|
| O000145|2026-03-04|     C00392|Customer_00392|   Mumbai|  West|      P007|             Tablet|Electronics|       5|  27807.87|           0|          NULL|   Shipped|  NULL|         139039.35|               0.0|         139039.35|  India|       Yes|      High|         Bulk|      In Progress|2026|    3|  4|
| O000210|2026-04-07|     C04814|Customer_04814|  Lucknow| North|      P004|    27 Inch Monitor|Electronics|       4|   17161.6|          10|          NULL|  Returned|  NULL|           68646.4| 6864.639999999999|61781.759999999995|  India|       Yes|      High|         Bulk|           Failed|2026|    4|  7|
| O000269|2026-05-03|     C04055|Customer_04055|    Delhi| North|      P002|     Wireless Mouse|Accessories|       2|    1499.9|           0|          NULL| Cancelled|  NULL|            2999.8|               0.0|            2999.8|  India|        No|       Low|      Regular|           Failed|2026|    5|  3|
| O000342|2026-10-01|     C01634|Customer_01634|Ahmedabad|  West|      P001|         Laptop Pro|Electronics|       3|  67671.22|          20|          NULL| Delivered|     2|         203013.66|         40602.732|        162410.928|  India|       Yes|      High|      Regular|        Completed|2026|   10|  1|
| O000350|2026-07-03|     C03357|Customer_03357|     Pune|  West|      P003|Mechanical Keyboard|Accessories|       1|   4534.66|           5|          NULL| Delivered|     1|           4534.66|           226.733|          4307.927|  India|        No|       Low|      Regular|        Completed|2026|    7|  3|
| O000367|2026-08-01|     C00381|Customer_00381|  Kolkata|  East|      P002|     Wireless Mouse|Accessories|       4|   1489.77|          20|          NULL|  Returned|  NULL|           5959.08|          1191.816|          4767.264|  India|        No|       Low|         Bulk|           Failed|2026|    8|  1|
| O000421|2026-03-22|     C00712|Customer_00712|     Pune|  West|      P007|             Tablet|Electronics|       3|  28760.09|          10|          NULL| Delivered|     1|          86280.27|          8628.027|         77652.243|  India|       Yes|      High|      Regular|        Completed|2026|    3| 22|
| O000472|2026-04-20|     C03073|Customer_03073|  Lucknow| North|      P012|          Bookshelf|  Furniture|       3|   7332.01|          15|          NULL|  Returned|  NULL|          21996.03|3299.4044999999996|        18696.6255|  India|        No|    Medium|      Regular|           Failed|2026|    4| 20|
| O000517|2026-01-06|     C01649|Customer_01649|     Pune|  West|      P005|       Office Chair|  Furniture|       1|   8723.19|          20|          NULL| Delivered|     3|           8723.19|1744.6380000000001| 6978.552000000001|  India|        No|       Low|      Regular|        Completed|2026|    1|  6|
| O000558|2026-04-10|     C04260|Customer_04260|Ahmedabad|  West|      P011|            Printer|Electronics|       2|  15521.97|           0|          NULL|Processing|  NULL|          31043.94|               0.0|          31043.94|  India|        No|    Medium|      Regular|      In Progress|2026|    4| 10|
| O000693|2026-04-06|     C01730|Customer_01730|  Chennai| South|      P002|     Wireless Mouse|Accessories|       5|   1442.24|           0|          NULL| Delivered|     2|            7211.2|               0.0|            7211.2|  India|        No|       Low|         Bulk|        Completed|2026|    4|  6|
| O000737|2026-06-12|     C03808|Customer_03808|  Lucknow| North|      P007|             Tablet|Electronics|       1|  27929.09|          10|          NULL| Cancelled|  NULL|          27929.09|          2792.909|         25136.181|  India|        No|    Medium|      Regular|           Failed|2026|    6| 12|
| O000801|2026-04-17|     C04438|Customer_04438|    Delhi| North|      P007|             Tablet|Electronics|       1|  26801.19|           0|          NULL| Delivered|     1|          26801.19|               0.0|          26801.19|  India|        No|    Medium|      Regular|        Completed|2026|    4| 17|
| O000973|2026-08-25|     C02330|Customer_02330|  Chennai| South|      P007|             Tablet|Electronics|       1|  29773.32|          20|          NULL| Delivered|     4|          29773.32| 5954.664000000001|         23818.656|  India|        No|    Medium|      Regular|        Completed|2026|    8| 25|
| O001065|2026-09-02|     C01103|Customer_01103|  Chennai| South|      P012|          Bookshelf|  Furniture|       5|   7999.61|          20|          NULL| Delivered|     4|39998.049999999996|           7999.61|31998.439999999995|  India|        No|    Medium|         Bulk|        Completed|2026|    9|  2|
| O001277|2026-05-20|     C03353|Customer_03353|Hyderabad| South|      P007|             Tablet|Electronics|       4|  27449.55|           5|          NULL| Delivered|     1|          109798.2|           5489.91|         104308.29|  India|       Yes|      High|         Bulk|        Completed|2026|    5| 20|
| O001445|2026-05-03|     C04201|Customer_04201|  Kolkata|  East|      P008|         Headphones|Accessories|       3|   3728.09|           0|          NULL| Delivered|     3|          11184.27|               0.0|          11184.27|  India|        No|       Low|      Regular|        Completed|2026|    5|  3|
+--------+----------+-----------+--------------+---------+------+----------+-------------------+-----------+--------+----------+------------+--------------+----------+------+------------------+------------------+------------------+-------+----------+----------+-------------+-----------------+----+-----+---+
only showing top 20 rows
Missing payment methods count: 2060

In [ ]:
from pyspark.sql import SparkSession
spark = SparkSession.builder \
    .appName("Widgets") \
    .getOrCreate()

In [ ]:
from google.colab import files,output
output.enable_custom_widget_manager()
import pandas as pd
import ipywidgets as widgets
from IPython.display import display
uploaded=files.upload()
df=pd.read_csv('manufacturing_production_extra_12k.csv')
print("Dataset loaded successfully!")
print("Number of records:", len(df))
display(df.head())

Saving manufacturing_production_extra_12k.csv to manufacturing_production_extra_12k (2).csv
Dataset loaded successfully!
Number of records: 12500

,production_id,production_date,plant_id,machine_id,operator_id,shift,product_code,product_family,units_planned,units_produced,defective_units,downtime_minutes,energy_kwh,temperature_c,vibration_mm_s,quality_status,maintenance_flag,supervisor
0,PR0120001,2026-06-01,PL05,MC024,OP0191,Evening,PMP-210,Pumps,293,292,10,44.0,120.42,70.59,2.21,Pass,Yes,Anita
1,PR0120002,2026-09-22,PL01,MC001,OP0461,Night,MTR-100,Motors,1009,897,25,59.0,317.23,81.74,3.03,Pass,No,Anita
2,PR0120003,2026-05-24,PL03,MC012,OP0451,Evening,MTR-100,Motors,960,983,34,0.0,350.82,67.29,2.01,Pass,No,Deepa
3,PR0120004,2026-09-12,PL04,MC016,OP0237,Night,CTL-130,Controllers,310,320,15,14.0,142.34,59.70,3.48,Pass,No,Anita
4,PR0120005,2026-02-04,PL04,MC018,OP0072,Morning,VLV-220,Valves,957,979,22,14.0,296.70,62.52,2.33,Pass,No,Harini

In [ ]:
# Function to create dropdown options
def create_options(column, all_label):
    values = sorted(df[column].dropna().astype(str).unique())

    return [(all_label, "__ALL__")] + [
        (value, value) for value in values
    ]


# 1. Plant dropdown
plant_dropdown = widgets.Dropdown(
    options=create_options("plant_id", "All Plants"),
    description="Plant:",
    style={"description_width": "initial"},
    layout=widgets.Layout(width="260px")
)


# 2. Product family dropdown
product_dropdown = widgets.Dropdown(
    options=create_options("product_family", "All Products"),
    description="Product Family:",
    style={"description_width": "initial"},
    layout=widgets.Layout(width="300px")
)


# 3. Quality status dropdown
quality_dropdown = widgets.Dropdown(
    options=create_options("quality_status", "All Statuses"),
    description="Quality:",
    style={"description_width": "initial"},
    layout=widgets.Layout(width="260px")
)


# 4. Slider for units produced
units = pd.to_numeric(df["units_produced"], errors="coerce").dropna()

units_slider = widgets.IntRangeSlider(
    value=(int(units.min()), int(units.max())),
    min=int(units.min()),
    max=int(units.max()),
    step=1,
    description="Units Produced:",
    continuous_update=False,
    style={"description_width": "initial"},
    layout=widgets.Layout(width="90%")
)

In [ ]:
from IPython.display import display
from google.colab import output

# Enable interactive widgets in Google Colab
output.enable_custom_widget_manager()

# Display all four widgets
display(widgets.VBox([
    plant_dropdown,
    product_dropdown,
    quality_dropdown,
    units_slider
]))

VBox(children=(Dropdown(description='Plant:', layout=Layout(width='260px'), options=(('All Plants', '__ALL__')…

In [ ]:
import pandas as pd
import ipywidgets as widgets
from IPython.display import display
from google.colab import files, output

uploaded = files.upload()
file_name = next(iter(uploaded))
df = pd.read_csv(file_name)

print("Dataset loaded successfully!")
print("Number of records:", len(df))
display(df.head())

Saving manufacturing_production_extra_12k.csv to manufacturing_production_extra_12k (10).csv
Dataset loaded successfully!
Number of records: 12500

,production_id,production_date,plant_id,machine_id,operator_id,shift,product_code,product_family,units_planned,units_produced,defective_units,downtime_minutes,energy_kwh,temperature_c,vibration_mm_s,quality_status,maintenance_flag,supervisor
0,PR0120001,2026-06-01,PL05,MC024,OP0191,Evening,PMP-210,Pumps,293,292,10,44.0,120.42,70.59,2.21,Pass,Yes,Anita
1,PR0120002,2026-09-22,PL01,MC001,OP0461,Night,MTR-100,Motors,1009,897,25,59.0,317.23,81.74,3.03,Pass,No,Anita
2,PR0120003,2026-05-24,PL03,MC012,OP0451,Evening,MTR-100,Motors,960,983,34,0.0,350.82,67.29,2.01,Pass,No,Deepa
3,PR0120004,2026-09-12,PL04,MC016,OP0237,Night,CTL-130,Controllers,310,320,15,14.0,142.34,59.70,3.48,Pass,No,Anita
4,PR0120005,2026-02-04,PL04,MC018,OP0072,Morning,VLV-220,Valves,957,979,22,14.0,296.70,62.52,2.33,Pass,No,Harini

In [ ]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, sum, avg, desc

spark = SparkSession.builder \
    .appName("LazyExecutionDemo") \
    .getOrCreate()

data = [
    (1, "Hyderabad", "Laptop", 2, 55000),
    (2, "Bangalore", "Mobile", 5, 20000),
    (3, "Chennai", "Tablet", 3, 15000),
    (4, "Hyderabad", "Mobile", 4, 22000),
    (5, "Mumbai", "Laptop", 1, 60000),
    (6, "Bangalore", "Tablet", 6, 12000),
    (7, "Chennai", "Laptop", 2, 58000),
    (8, "Mumbai", "Mobile", 8, 18000),
    (9, "Hyderabad", "Tablet", 5, 14000),
    (10, "Bangalore", "Laptop", 3, 52000),
    (11, "Mumbai", "Tablet", 7, 13000),
    (12, "Chennai", "Mobile", 6, 21000)
]

columns = ["sale_id", "city", "product", "quantity", "price"]

df = spark.createDataFrame(data, columns)

df.show()

+-------+---------+-------+--------+-----+
|sale_id|     city|product|quantity|price|
+-------+---------+-------+--------+-----+
|      1|Hyderabad| Laptop|       2|55000|
|      2|Bangalore| Mobile|       5|20000|
|      3|  Chennai| Tablet|       3|15000|
|      4|Hyderabad| Mobile|       4|22000|
|      5|   Mumbai| Laptop|       1|60000|
|      6|Bangalore| Tablet|       6|12000|
|      7|  Chennai| Laptop|       2|58000|
|      8|   Mumbai| Mobile|       8|18000|
|      9|Hyderabad| Tablet|       5|14000|
|     10|Bangalore| Laptop|       3|52000|
|     11|   Mumbai| Tablet|       7|13000|
|     12|  Chennai| Mobile|       6|21000|
+-------+---------+-------+--------+-----+

In [ ]:
filtered_df=df.filter(col("quantity")>3)
print("Transformation created")
selected_df=filtered_df.select(
    "city","product","quantity"
)
print("Another transformation created")
selected_df.show()

In [ ]:
step1 = df.filter(col("quantity")>=3)
step2=step1.withColumn(
    "revenue",
    col("quantity") * col("price")
)
step3=step2.groupBy("city").agg(
    sum("revenue").alias("total_revenue")
)
step4=step3.orderBy(desc("total_revenue"))
print("All transformations defined")
step4.show()

In [ ]:
result=df.filter(col("price") > 20000) \
                 .select("city", "product", "price") \
                 .orderBy(desc("price"))
result.explain()

In [ ]:
result.show()

+---------+-------+-----+
|     city|product|price|
+---------+-------+-----+
|   Mumbai| Laptop|60000|
|  Chennai| Laptop|58000|
|Hyderabad| Laptop|55000|
|Bangalore| Laptop|52000|
|Hyderabad| Mobile|22000|
|  Chennai| Mobile|21000|
+---------+-------+-----+

In [ ]:
high_value_sales=df.filter(col("price")>20000)
high_value_sales.show()
print("Total records:", high_value_sales.count())
records=high_value_sales.collect()
print(records)

In [ ]:
from google.colab import files
uploaded = files.upload()
from google.colab import files
uploaded = files.upload()
from google.colab import files
uploaded = files.upload()

Saving lazy_execution_sales_25000.csv to lazy_execution_sales_25000.csv

Saving lazy_execution_products.csv to lazy_execution_products.csv

Saving lazy_execution_stores.csv to lazy_execution_stores.csv

In [ ]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, sum, avg, count, desc
spark = SparkSession.builder \
    .appName("LazyExecutionExercises") \
    .getOrCreate()
sales_df = spark.read.csv("lazy_execution_sales_25000.csv", header=True, inferSchema=True)
products_df = spark.read.csv("lazy_execution_products.csv", header=True, inferSchema=True)
stores_df = spark.read.csv("lazy_execution_stores.csv", header=True, inferSchema=True)

In [ ]:
filtered_sales = sales_df.filter(col("quantity") > 5)

In [ ]:
selected_sales = sales_df.select("order_id", "product_id", "quantity", "unit_price")
selected_sales.show(10)

+--------+----------+--------+----------+
|order_id|product_id|quantity|unit_price|
+--------+----------+--------+----------+
| O000001|      P002|       3|      2999|
| O000002|      P014|       6|     29999|
| O000003|      P008|       6|     22999|
| O000004|      P008|       7|     22999|
| O000005|      P007|       2|     79999|
| O000006|      P005|       8|      2499|
| O000007|      P010|       8|      3999|
| O000008|      P002|       9|      2999|
| O000009|      P007|       5|     79999|
| O000010|      P006|       5|     55999|
+--------+----------+--------+----------+
only showing top 10 rows

In [ ]:
high_price_count = sales_df.filter(col("unit_price") > 20000).count()
print(f"Number of records with unit price > 20,000: {high_price_count}")

Number of records with unit price > 20,000: 6560

In [ ]:
gross_sales = sales_df.withColumn("gross_amount", col("quantity") * col("unit_price"))
gross_sales.explain()
gross_sales.select("order_id", "quantity", "unit_price", "gross_amount").show(10)

== Physical Plan ==
*(1) Project [order_id#128, order_date#129, store_id#130, product_id#131, quantity#132, unit_price#133, discount_pct#134, payment_method#135, order_status#136, sales_channel#137, (quantity#132 * unit_price#133) AS gross_amount#214]
+- FileScan csv [order_id#128,order_date#129,store_id#130,product_id#131,quantity#132,unit_price#133,discount_pct#134,payment_method#135,order_status#136,sales_channel#137] Batched: false, DataFilters: [], Format: CSV, Location: InMemoryFileIndex(1 paths)[file:/content/lazy_execution_sales_25000.csv], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<order_id:string,order_date:date,store_id:string,product_id:string,quantity:int,unit_price:...


+--------+--------+----------+------------+
|order_id|quantity|unit_price|gross_amount|
+--------+--------+----------+------------+
| O000001|       3|      2999|        8997|
| O000002|       6|     29999|      179994|
| O000003|       6|     22999|      137994|
| O000004|       7|     22999|      160993|
| O000005|       2|     79999|      159998|
| O000006|       8|      2499|       19992|
| O000007|       8|      3999|       31992|
| O000008|       9|      2999|       26991|
| O000009|       5|     79999|      399995|
| O000010|       5|     55999|      279995|
+--------+--------+----------+------------+
only showing top 10 rows

In [ ]:
completed_sorted = sales_df.filter(col("order_status") == "Completed") \
                           .orderBy(col("unit_price").desc())

top_10_records = completed_sorted.take(10)
for record in top_10_records:
    print(record)

Row(order_id='O000085', order_date=datetime.date(2026, 4, 22), store_id='S03', product_id='P007', quantity=4, unit_price=79999, discount_pct=0, payment_method='Card', order_status='Completed', sales_channel='Online')
Row(order_id='O000290', order_date=datetime.date(2026, 6, 26), store_id='S06', product_id='P007', quantity=3, unit_price=79999, discount_pct=10, payment_method='Net Banking', order_status='Completed', sales_channel='Online')
Row(order_id='O000098', order_date=datetime.date(2026, 4, 15), store_id='S05', product_id='P007', quantity=1, unit_price=79999, discount_pct=5, payment_method='Net Banking', order_status='Completed', sales_channel='Online')
Row(order_id='O000005', order_date=datetime.date(2026, 3, 14), store_id='S06', product_id='P007', quantity=2, unit_price=79999, discount_pct=0, payment_method='Cash', order_status='Completed', sales_channel='Online')
Row(order_id='O000107', order_date=datetime.date(2026, 5, 24), store_id='S05', product_id='P007', quantity=9, unit_price=79999, discount_pct=20, payment_method='Cash', order_status='Completed', sales_channel='Online')
Row(order_id='O000015', order_date=datetime.date(2026, 4, 20), store_id='S08', product_id='P007', quantity=7, unit_price=79999, discount_pct=15, payment_method='Net Banking', order_status='Completed', sales_channel='In Store')
Row(order_id='O000120', order_date=datetime.date(2026, 5, 27), store_id='S03', product_id='P007', quantity=8, unit_price=79999, discount_pct=15, payment_method='Net Banking', order_status='Completed', sales_channel='Online')
Row(order_id='O000057', order_date=datetime.date(2026, 1, 28), store_id='S01', product_id='P007', quantity=6, unit_price=79999, discount_pct=10, payment_method='Cash', order_status='Completed', sales_channel='In Store')
Row(order_id='O000140', order_date=datetime.date(2026, 1, 24), store_id='S01', product_id='P007', quantity=3, unit_price=79999, discount_pct=5, payment_method='Net Banking', order_status='Completed', sales_channel='Online')
Row(order_id='O000076', order_date=datetime.date(2026, 2, 23), store_id='S06', product_id='P007', quantity=8, unit_price=79999, discount_pct=15, payment_method='UPI', order_status='Completed', sales_channel='Online')

In [ ]:
sales_df.filter(col("order_status") == "Completed") \
        .withColumn("gross_amount", col("quantity") * col("unit_price")) \
        .select("order_id", "store_id", "product_id", "quantity", "gross_amount") \
        .orderBy(col("gross_amount").desc()) \
        .show(10)

+--------+--------+----------+--------+------------+
|order_id|store_id|product_id|quantity|gross_amount|
+--------+--------+----------+--------+------------+
| O001170|     S01|      P007|       9|      719991|
| O002603|     S01|      P007|       9|      719991|
| O001201|     S05|      P007|       9|      719991|
| O000107|     S05|      P007|       9|      719991|
| O001209|     S02|      P007|       9|      719991|
| O000456|     S04|      P007|       9|      719991|
| O001300|     S03|      P007|       9|      719991|
| O000615|     S08|      P007|       9|      719991|
| O001595|     S05|      P007|       9|      719991|
| O000737|     S08|      P007|       9|      719991|
+--------+--------+----------+--------+------------+
only showing top 10 rows

In [ ]:
sales_df.filter(col("discount_pct") >= 10) \
        .withColumn("discounted_sales_amount", (col("quantity") * col("unit_price")) * (1 - col("discount_pct") / 100)) \
        .orderBy(col("discounted_sales_amount").desc()) \
        .show(15)

+--------+----------+--------+----------+--------+----------+------------+--------------+------------+-------------+-----------------------+
|order_id|order_date|store_id|product_id|quantity|unit_price|discount_pct|payment_method|order_status|sales_channel|discounted_sales_amount|
+--------+----------+--------+----------+--------+----------+------------+--------------+------------+-------------+-----------------------+
| O006653|2026-06-29|     S01|      P007|       9|     79999|          10|          Card|   Cancelled|       Online|               647991.9|
| O011893|2026-03-26|     S07|      P007|       9|     79999|          10|           UPI|   Completed|       Online|               647991.9|
| O006699|2026-06-25|     S05|      P007|       9|     79999|          10|   Net Banking|   Completed|       Online|               647991.9|
| O003108|2026-02-23|     S08|      P007|       9|     79999|          10|   Net Banking|   Completed|     In Store|               647991.9|
| O007743|2026-05-22|     S08|      P007|       9|     79999|          10|   Net Banking|   Completed|     In Store|               647991.9|
| O000264|2026-02-24|     S07|      P007|       9|     79999|          10|           UPI|   Completed|       Online|               647991.9|
| O009316|2026-04-05|     S03|      P007|       9|     79999|          10|   Net Banking|   Completed|       Online|               647991.9|
| O000367|2026-01-24|     S01|      P007|       9|     79999|          10|          Card|   Completed|     In Store|               647991.9|
| O009625|2026-05-02|     S03|      P007|       9|     79999|          10|   Net Banking|   Completed|       Online|               647991.9|
| O003974|2026-05-23|     S04|      P007|       9|     79999|          10|          Card|   Completed|     In Store|               647991.9|
| O009646|2026-01-01|     S06|      P007|       9|     79999|          10|           UPI|    Returned|     In Store|               647991.9|
| O002907|2026-01-31|     S05|      P007|       9|     79999|          10|           UPI|    Returned|     In Store|               647991.9|
| O010062|2026-04-27|     S03|      P007|       9|     79999|          10|           UPI|   Completed|       Online|               647991.9|
| O004940|2026-02-16|     S05|      P007|       9|     79999|          10|          Card|   Completed|       Online|               647991.9|
| O001209|2026-04-10|     S02|      P007|       9|     79999|          10|           UPI|   Completed|       Online|               647991.9|
+--------+----------+--------+----------+--------+----------+------------+--------------+------------+-------------+-----------------------+
only showing top 15 rows

In [ ]:
sales_df.groupBy("payment_method") \
        .agg(sum("quantity").alias("total_quantity")) \
        .orderBy(col("total_quantity").desc()) \
        .show()

+--------------+--------------+
|payment_method|total_quantity|
+--------------+--------------+
|          Cash|         31754|
|          Card|         31327|
|           UPI|         30894|
|   Net Banking|         30889|
+--------------+--------------+

In [ ]:
sales_df.groupBy("sales_channel", "order_status") \
        .agg(count("*").alias("transaction_count")) \
        .show()

+-------------+------------+-----------------+
|sales_channel|order_status|transaction_count|
+-------------+------------+-----------------+
|       Online|   Completed|            10797|
|     In Store|   Cancelled|              592|
|       Online|    Returned|              987|
|       Online|   Cancelled|              633|
|     In Store|    Returned|             1013|
|     In Store|   Completed|            10978|
+-------------+------------+-----------------+

In [ ]:
subset_df = sales_df.select("order_id", "store_id", "product_id", "quantity") \
                    .drop("store_id")

first_record = subset_df.first()
print(first_record)

Row(order_id='O000001', product_id='P002', quantity=3)

In [ ]:
sales_df.join(products_df, "product_id", "inner") \
        .select("product_name", "category", "quantity", "unit_price") \
        .show(20)

+-------------------+-----------+--------+----------+
|       product_name|   category|quantity|unit_price|
+-------------------+-----------+--------+----------+
|Mechanical Keyboard|Accessories|       3|      2999|
|      Smartphone 5G|    Mobiles|       6|     29999|
|     Android Tablet|    Tablets|       6|     22999|
|     Android Tablet|    Tablets|       7|     22999|
|          Laptop 16|  Computers|       2|     79999|
|          Webcam HD|Accessories|       8|      2499|
|  Bluetooth Speaker|      Audio|       8|      3999|
|Mechanical Keyboard|Accessories|       9|      2999|
|          Laptop 16|  Computers|       5|     79999|
|          Laptop 14|  Computers|       5|     55999|
|          Laptop 16|  Computers|       1|     79999|
|  Bluetooth Speaker|      Audio|       9|      3999|
|   External HDD 2TB|    Storage|       6|      5999|
|          Webcam HD|Accessories|       8|      2499|
|          Laptop 16|  Computers|       7|     79999|
|          Laptop 14|  Computers|       1|     55999|
|    27-inch Monitor|   Displays|       9|     16999|
|   Portable SSD 1TB|    Storage|       7|      6999|
|      Smartphone 5G|    Mobiles|       5|     29999|
|  Bluetooth Speaker|      Audio|       7|      3999|
+-------------------+-----------+--------+----------+
only showing top 20 rows

In [ ]:
sales_df.join(stores_df, "store_id", "inner") \
        .groupBy("city") \
        .agg(sum("quantity").alias("total_quantity_sold")) \
        .show()

+---------+-------------------+
|     city|total_quantity_sold|
+---------+-------------------+
|  Chennai|              15727|
|   Mumbai|              15489|
|  Kolkata|              15619|
|     Pune|              15407|
|    Delhi|              15101|
|Bengaluru|              15718|
|Hyderabad|              15784|
|   Jaipur|              16019|
+---------+-------------------+

In [ ]:
sales_df.join(products_df, "product_id", "inner") \
        .join(stores_df, "store_id", "inner") \
        .filter(col("order_status") == "Completed") \
        .withColumn("revenue", col("quantity") * col("unit_price")) \
        .groupBy("category", "region") \
        .agg(sum("revenue").alias("total_revenue")) \
        .orderBy("category", "region") \
        .show(20)

+-----------+------+-------------+
|   category|region|total_revenue|
+-----------+------+-------------+
|Accessories|  East|      9093361|
|Accessories| North|     18463455|
|Accessories| South|     28139018|
|Accessories|  West|     18351560|
|      Audio|  East|     12043135|
|      Audio| North|     24327211|
|      Audio| South|     34629665|
|      Audio|  West|     25317111|
|  Computers|  East|    122990192|
|  Computers| North|    240756425|
|  Computers| South|    371954527|
|  Computers|  West|    221092729|
|   Displays|  East|     13616199|
|   Displays| North|     32468090|
|   Displays| South|     45761308|
|   Displays|  West|     28286336|
|    Mobiles|  East|     41178126|
|    Mobiles| North|     75482543|
|    Mobiles| South|    120674524|
|    Mobiles|  West|     80372388|
+-----------+------+-------------+
only showing top 20 rows

In [ ]:
sales_df.filter(col("order_status") == "Completed") \
        .join(products_df, "product_id", "inner") \
        .withColumn("discounted_revenue", (col("quantity") * col("unit_price")) * (1 - col("discount_pct") / 100)) \
        .groupBy("product_name") \
        .agg(sum("discounted_revenue").alias("total_discounted_revenue")) \
        .orderBy(col("total_discounted_revenue").desc()) \
        .show(5)

+---------------+------------------------+
|   product_name|total_discounted_revenue|
+---------------+------------------------+
|      Laptop 16|    5.2272546585000014E8|
|      Laptop 14|     3.830051604999999E8|
|  Smartphone 5G|     2.060406317500002E8|
| Android Tablet|    1.5040656029999995E8|
|27-inch Monitor|    1.1406074015000013E8|
+---------------+------------------------+
only showing top 5 rows

In [ ]:
t1 = sales_df.filter(col("order_status") == "Completed")
print("Transformation 1 applied (Filter). No execution yet.")

t2 = t1.select("order_id", "store_id", "product_id", "quantity", "unit_price")
print("Transformation 2 applied (Select). No execution yet.")

t3 = t2.withColumn("revenue", col("quantity") * col("unit_price"))
print("Transformation 3 applied (WithColumn). No execution yet.")

t4 = t3.groupBy("store_id").agg(sum("revenue").alias("store_revenue"))
print("Transformation 4 applied (GroupBy). No execution yet.")

t5 = t4.orderBy(col("store_revenue").desc())
print("Transformation 5 applied (OrderBy). No execution yet.")
t5.show()
print("Action triggered! Spark executed the entire DAG of transformations now.")

Transformation 1 applied (Filter). No execution yet.
Transformation 2 applied (Select). No execution yet.
Transformation 3 applied (WithColumn). No execution yet.
Transformation 4 applied (GroupBy). No execution yet.
Transformation 5 applied (OrderBy). No execution yet.
+--------+-------------+
|store_id|store_revenue|
+--------+-------------+
|     S07|    237480949|
|     S02|    236373766|
|     S03|    233939468|
|     S01|    231828344|
|     S08|    229851332|
|     S04|    220509065|
|     S06|    216437396|
|     S05|    214072770|
+--------+-------------+

Action triggered! Spark executed the entire DAG of transformations now.

In [ ]:
filtered_df = sales_df.filter(col("unit_price") > 15000)
filtered_df.explain(True)
print("Calling show():")
filtered_df.show(5)
print("Calling count():")
print("Count:", filtered_df.count())

== Parsed Logical Plan ==
'Filter '`>`('unit_price, 15000)
+- Relation [order_id#128,order_date#129,store_id#130,product_id#131,quantity#132,unit_price#133,discount_pct#134,payment_method#135,order_status#136,sales_channel#137] csv

== Analyzed Logical Plan ==
order_id: string, order_date: date, store_id: string, product_id: string, quantity: int, unit_price: int, discount_pct: int, payment_method: string, order_status: string, sales_channel: string
Filter (unit_price#133 > 15000)
+- Relation [order_id#128,order_date#129,store_id#130,product_id#131,quantity#132,unit_price#133,discount_pct#134,payment_method#135,order_status#136,sales_channel#137] csv

== Optimized Logical Plan ==
Filter (isnotnull(unit_price#133) AND (unit_price#133 > 15000))
+- Relation [order_id#128,order_date#129,store_id#130,product_id#131,quantity#132,unit_price#133,discount_pct#134,payment_method#135,order_status#136,sales_channel#137] csv

== Physical Plan ==
*(1) Filter (isnotnull(unit_price#133) AND (unit_price#133 > 15000))
+- FileScan csv [order_id#128,order_date#129,store_id#130,product_id#131,quantity#132,unit_price#133,discount_pct#134,payment_method#135,order_status#136,sales_channel#137] Batched: false, DataFilters: [isnotnull(unit_price#133), (unit_price#133 > 15000)], Format: CSV, Location: InMemoryFileIndex(1 paths)[file:/content/lazy_execution_sales_25000.csv], PartitionFilters: [], PushedFilters: [IsNotNull(unit_price), GreaterThan(unit_price,15000)], ReadSchema: struct<order_id:string,order_date:date,store_id:string,product_id:string,quantity:int,unit_price:...

Calling show():
+--------+----------+--------+----------+--------+----------+------------+--------------+------------+-------------+
|order_id|order_date|store_id|product_id|quantity|unit_price|discount_pct|payment_method|order_status|sales_channel|
+--------+----------+--------+----------+--------+----------+------------+--------------+------------+-------------+
| O000002|2026-05-29|     S07|      P014|       6|     29999|           0|          Card|   Completed|       Online|
| O000003|2026-06-27|     S06|      P008|       6|     22999|           0|          Card|   Completed|     In Store|
| O000004|2026-04-10|     S03|      P008|       7|     22999|          15|          Cash|   Completed|       Online|
| O000005|2026-03-14|     S06|      P007|       2|     79999|           0|          Cash|   Completed|       Online|
| O000009|2026-01-15|     S03|      P007|       5|     79999|          15|          Cash|   Completed|     In Store|
+--------+----------+--------+----------+--------+----------+------------+--------------+------------+-------------+
only showing top 5 rows
Calling count():
Count: 8134

In [ ]:
grouped_df = sales_df.join(products_df, "product_id", "inner") \
                     .groupBy("category") \
                     .agg(sum("quantity").alias("total_quantity"))
results = grouped_df.collect()
for row in results:
    print(row)

Row(category='Computers', total_quantity=16258)
Row(category='Displays', total_quantity=7870)
Row(category='Mobiles', total_quantity=16572)
Row(category='Accessories', total_quantity=41839)
Row(category='Storage', total_quantity=17251)
Row(category='Audio', total_quantity=17159)
Row(category='Tablets', total_quantity=7915)

In [ ]:
result_df = sales_df.filter(col("order_status") == "Completed") \
                    .withColumn("discounted_revenue", (col("quantity") * col("unit_price")) * (1 - col("discount_pct") / 100))
result_df.write.mode("overwrite").parquet("completed_sales_output.parquet")
print("DataFrame successfully written to Parquet!")

DataFrame successfully written to Parquet!

In [ ]:
from google.colab import files
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName("SalesAnalysis").getOrCreate()
# Browse and select multiple CSV files
uploaded = files.upload()
# Load selected CSV files into PySpark DataFrames
dataframes = {}
for filename in uploaded.keys():
    df = spark.read.csv(filename, header=True, inferSchema=True)
    dataframes[filename] = df
    print(f"\nFile: {filename}")
    print("Records:", df.count())
    df.show(5)

Saving lazy_execution_stores (1).csv to lazy_execution_stores (1) (3).csv

File: lazy_execution_stores (1) (3).csv
Records: 8
+--------+---------+------+-----------+
|store_id|     city|region| store_type|
+--------+---------+------+-----------+
|     S01|Hyderabad| South|       Mall|
|     S02|Bengaluru| South|High Street|
|     S03|  Chennai| South|       Mall|
|     S04|   Mumbai|  West|High Street|
|     S05|     Pune|  West|       Mall|
+--------+---------+------+-----------+
only showing top 5 rows

In [ ]:
sales_df = spark.read.csv("path/to/sales_data.csv", header=True, inferSchema=True)

In [ ]:
completed_df = sales_df.filter(F.col("order_status") == "Completed")

print("Transformation created")
print("Completed Orders:", completed_df.count())

In [ ]:
completed_df.cache()
print("Is Cached:", completed_df.is_cached)

completed_df.count()
completed_df.show(10)
completed_df.groupBy("product_id").count().show()

In [ ]:
high_quality_df = sales_df.filter(
    F.col("quantity") > 5
)

high_quality_df.persist(
    StorageLevel.MEMORY_AND_DISK
)

high_quality_df.count()
high_quality_df.show(10)
print(high_quality_df.storageLevel)

NameError: name 'sales_df' is not defined

In [ ]:
from google.colab import files
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName("SalesAnalysis").getOrCreate()
# Browse and select multiple CSV files
uploaded = files.upload()
# Load selected CSV files into PySpark DataFrames
dataframes = {}
for filename in uploaded.keys():
    df = spark.read.csv(filename, header=True, inferSchema=True)
    dataframes[filename] = df
    print(f"\nFile: {filename}")
    print("Records:", df.count())
    df.show(5)

In [23]:
import pyspark.sql.functions as F
sales_df = dataframes['lazy_execution_sales_25000 (1) (2).csv']

completed_df = sales_df.filter(F.col("order_status") == "Completed")

print("Transformation created successfully!")
print("Completed Orders:", completed_df.count())

Transformation created successfully!
Completed Orders: 21775

In [24]:
completed_df.cache()
print("Is Cached:", completed_df.is_cached)

completed_df.count()
completed_df.show(10)
completed_df.groupBy("product_id").count().show()

Is Cached: True
+--------+----------+--------+----------+--------+----------+------------+--------------+------------+-------------+
|order_id|order_date|store_id|product_id|quantity|unit_price|discount_pct|payment_method|order_status|sales_channel|
+--------+----------+--------+----------+--------+----------+------------+--------------+------------+-------------+
| O000001|2026-06-22|     S04|      P002|       3|      2999|          10|   Net Banking|   Completed|     In Store|
| O000002|2026-05-29|     S07|      P014|       6|     29999|           0|          Card|   Completed|       Online|
| O000003|2026-06-27|     S06|      P008|       6|     22999|           0|          Card|   Completed|     In Store|
| O000004|2026-04-10|     S03|      P008|       7|     22999|          15|          Cash|   Completed|       Online|
| O000005|2026-03-14|     S06|      P007|       2|     79999|           0|          Cash|   Completed|       Online|
| O000006|2026-04-05|     S08|      P005|       8|      2499|           0|           UPI|   Completed|     In Store|
| O000007|2026-02-27|     S03|      P010|       8|      3999|          10|           UPI|   Completed|       Online|
| O000008|2026-03-21|     S07|      P002|       9|      2999|           0|          Card|   Completed|     In Store|
| O000009|2026-01-15|     S03|      P007|       5|     79999|          15|          Cash|   Completed|     In Store|
| O000010|2026-06-01|     S02|      P006|       5|     55999|           0|   Net Banking|   Completed|     In Store|
+--------+----------+--------+----------+--------+----------+------------+--------------+------------+-------------+
only showing top 10 rows
+----------+-----+
|product_id|count|
+----------+-----+
|      P012| 1467|
|      P007| 1377|
|      P003| 1469|
|      P010| 1493|
|      P006| 1467|
|      P011| 1482|
|      P004| 1398|
|      P002| 1418|
|      P001| 1512|
|      P008| 1390|
|      P013| 1510|
|      P009| 1428|
|      P015| 1418|
|      P005| 1483|
|      P014| 1463|
+----------+-----+

In [27]:
from pyspark import StorageLevel
import pyspark.sql.functions as F
high_quality_df = sales_df.filter(
    F.col("quantity") > 5
)
high_quality_df.persist(
    StorageLevel.MEMORY_AND_DISK
)
high_quality_df.count()
high_quality_df.show(10)
print(high_quality_df.storageLevel)

+--------+----------+--------+----------+--------+----------+------------+--------------+------------+-------------+
|order_id|order_date|store_id|product_id|quantity|unit_price|discount_pct|payment_method|order_status|sales_channel|
+--------+----------+--------+----------+--------+----------+------------+--------------+------------+-------------+
| O000002|2026-05-29|     S07|      P014|       6|     29999|           0|          Card|   Completed|       Online|
| O000003|2026-06-27|     S06|      P008|       6|     22999|           0|          Card|   Completed|     In Store|
| O000004|2026-04-10|     S03|      P008|       7|     22999|          15|          Cash|   Completed|       Online|
| O000006|2026-04-05|     S08|      P005|       8|      2499|           0|           UPI|   Completed|     In Store|
| O000007|2026-02-27|     S03|      P010|       8|      3999|          10|           UPI|   Completed|       Online|
| O000008|2026-03-21|     S07|      P002|       9|      2999|           0|          Card|   Completed|     In Store|
| O000012|2026-01-04|     S01|      P010|       9|      3999|          10|           UPI|    Returned|       Online|
| O000013|2026-04-25|     S03|      P013|       6|      5999|           0|           UPI|   Completed|       Online|
| O000014|2026-06-13|     S06|      P005|       8|      2499|          10|          Card|   Completed|       Online|
| O000015|2026-04-20|     S08|      P007|       7|     79999|          15|   Net Banking|   Completed|     In Store|
+--------+----------+--------+----------+--------+----------+------------+--------------+------------+-------------+
only showing top 10 rows
Disk Memory Serialized 1x Replicated

In [28]:
print("Total Records:", sales_df.count())
print("Number of Partitions:",
      sales_df.rdd.getNumPartitions())

Total Records: 25000
Number of Partitions: 1

In [32]:
partitioned_df = sales_df.repartition(8)

print("Original Partitions:", sales_df.rdd.getNumPartitions())
print("New Partitions:", partitioned_df.rdd.getNumPartitions())

partitioned_df.count()

Original Partitions: 1
New Partitions: 8

25000

In [ ]:
df8 = sales_df.repartition(8)

df_partition = df8.repartition(3)
df_coalesce = df8.coalesce(3)

print("Repartition:", df_partition.rdd.getNumPartitions())
print("Coalesce:", df_coalesce.rdd.getNumPartitions())

print("REPARTITION PLAN")
df_partition.explain()

print("COALESCE PLAN")
df_coalesce.explain()

In [39]:
print("Current number of partitions:", sales_df.rdd.getNumPartitions())

Current number of partitions: 1

In [40]:
df_12 = sales_df.repartition(12)
print("Increased partitions:", df_12.rdd.getNumPartitions())

Increased partitions: 12

In [41]:
print("Number of records in each partition:", sales_df.rdd.glom().map(len).collect())

Number of records in each partition: [25000]

In [42]:
df_product_6 = sales_df.repartition(6, "product_id")
print("Partitions using product_id:", df_product_6.rdd.getNumPartitions())

Partitions using product_id: 6

In [43]:
df_4 = df_12.coalesce(4)
print("Reduced partitions using coalesce:", df_4.rdd.getNumPartitions())

Reduced partitions using coalesce: 4